In [2]:
!nvidia-smi

Wed Jun 10 06:42:47 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:DB:00.0 Off |                    0 |
| N/A   26C    P0             79W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
!pip install -q "ultralytics==8.4.62"

In [4]:
!pip install -q gdown

In [6]:
!gdown "14Z2n-BfgaKreJuSwR_Hdtm_ItsKXoVrN" -O /workspace/v4_real_final_20260610_yolo_export.tar.gz

Downloading...
From (original): https://drive.google.com/uc?id=14Z2n-BfgaKreJuSwR_Hdtm_ItsKXoVrN
From (redirected): https://drive.google.com/uc?id=14Z2n-BfgaKreJuSwR_Hdtm_ItsKXoVrN&confirm=t&uuid=cb6959b1-b504-4d87-a0fb-1250044c3f1d
To: /workspace/v4_real_final_20260610_yolo_export.tar.gz
100%|██████████████████████████████████████| 8.16G/8.16G [00:56<00:00, 145MB/s]

In [7]:
!ls -lh /workspace/v4_real_final_20260610_yolo_export.tar.gz

-rw-rw-rw- 1 root root 7.7G Jun 10 06:48 /workspace/v4_real_final_20260610_yolo_export.tar.gz

In [8]:
from pathlib import Path

for p in Path("/workspace").iterdir():
    size_gb = p.stat().st_size / 1024**3 if p.is_file() else 0
    print(p.name, f"{size_gb:.2f} GB" if p.is_file() else "DIR")

v4_real_final_20260610_yolo_export.tar.gz 7.65 GB
.cache DIR
.ipynb_checkpoints DIR
Untitled.ipynb 0.00 GB

In [9]:
from pathlib import Path
import tarfile

PROJECT = Path("/workspace/uavape_v4_model_benchmark")
DATA_ROOT = PROJECT / "datasets"
DATA_DIR = DATA_ROOT / "v4_real_final_20260610"
ARCHIVE = Path("/workspace/v4_real_final_20260610_yolo_export.tar.gz")

DATA_ROOT.mkdir(parents=True, exist_ok=True)

if DATA_DIR.exists():
    print("Dataset already exists:", DATA_DIR)
else:
    print("Extracting archive...")
    with tarfile.open(ARCHIVE, "r:gz") as tar:
        tar.extractall(DATA_ROOT)
    print("Done")

print("DATA_DIR exists:", DATA_DIR.exists())

Extracting archive...
Done
DATA_DIR exists: True

In [10]:
removed = 0
for p in DATA_DIR.rglob("._*"):
    p.unlink()
    removed += 1

print("Removed sidecar files:", removed)

Removed sidecar files: 2418

In [11]:
import yaml

yaml_path = DATA_DIR / "dataset.yaml"
data_yaml = yaml.safe_load(yaml_path.read_text())
data_yaml["path"] = str(DATA_DIR)

with open(yaml_path, "w") as f:
    yaml.safe_dump(data_yaml, f, sort_keys=False)

print(yaml_path.read_text())

path: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610
train: images/train
val: images/val
test: images/test
nc: 2
names:
  0: vape
  1: lighter

In [12]:
from pathlib import Path
from collections import Counter

def count_split(split):
    img_dir = DATA_DIR / "images" / split
    lab_dir = DATA_DIR / "labels" / split

    images = sorted([
        p for p in img_dir.iterdir()
        if p.is_file()
        and p.suffix.lower() in {".jpg", ".jpeg", ".png"}
        and not p.name.startswith("._")
    ])

    labels = sorted([
        p for p in lab_dir.glob("*.txt")
        if p.is_file()
        and not p.name.startswith("._")
    ])

    class_counts = Counter()
    boxes = 0

    for label in labels:
        for line in label.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            cls = int(line.split()[0])
            class_counts[cls] += 1
            boxes += 1

    missing_labels = [
        img.name for img in images
        if not (lab_dir / f"{img.stem}.txt").exists()
    ]

    missing_images = [
        lab.name for lab in labels
        if not (img_dir / f"{lab.stem}.jpg").exists()
    ]

    return {
        "split": split,
        "images": len(images),
        "labels": len(labels),
        "boxes": boxes,
        "vape_boxes": class_counts[0],
        "lighter_boxes": class_counts[1],
        "missing_labels": len(missing_labels),
        "missing_images": len(missing_images),
    }

for split in ["train", "val", "test"]:
    print(count_split(split))

{'split': 'train', 'images': 837, 'labels': 837, 'boxes': 1317, 'vape_boxes': 870, 'lighter_boxes': 447, 'missing_labels': 0, 'missing_images': 0}
{'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100, 'missing_labels': 0, 'missing_images': 0}
{'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165, 'missing_labels': 0, 'missing_images': 0}

In [13]:
!rm /workspace/v4_real_final_20260610_yolo_export.tar.gz

In [14]:
from ultralytics import YOLO
from pathlib import Path

PROJECT = Path("/workspace/uavape_v4_model_benchmark")
RUN = {"model": "yolo26s.pt", "imgsz": 640}

model = YOLO(RUN["model"])

results = model.train(
    data=str(yaml_path),
    project=str(PROJECT / "runs"),
    name=f'v4_{Path(RUN["model"]).stem}_img{RUN["imgsz"]}',
    imgsz=RUN["imgsz"],
    epochs=100,
    batch=32,
    device=0,
    workers=8,
    seed=42,
    deterministic=True,
    cos_lr=True,
    patience=100,
    exist_ok=True,
    plots=True,
)

WARNING ⚠️ user config directory '/root/.config/Ultralytics' is not writable, using '/tmp/Ultralytics'. Set YOLO_CONFIG_DIR to override.
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/tmp/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26s.pt to 'yolo26s.pt': 100% ━━━━━━━━━━━━ 19.5MB 143.3MB/s 0.1s
New https://pypi.org/project/ultralytics/8.4.63 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_yolo26s_img640, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/tmp/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 178.3MB/s 0.0s
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    933412  ultralytics.nn.modules.head.Detect           [2, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,949,412 parameters, 9,949,412 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 203.1MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.2±0.0 ms, read: 497.7±48.4 MB/s, size: 6617.1 KB)
train: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/labels/train... 837 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 837/837 774.4it/s 1.1s
train: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/labels/train.cache
val: Fast image access ✅ (ping: 0.2±0.1 ms, read: 343.8±103.6 MB/s, size: 4522.9 KB)
val: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/labels/val... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183 946.7it/s 0.2s
val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
val: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      9.09G      1.636      12.12   0.005941          5        640: 100% ━━━━━━━━━━━━ 27/27 1.4s/it 38.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s
                   all        183        302      0.173      0.171      0.135     0.0889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      11.5G       1.78      3.601   0.006621          5        640: 100% ━━━━━━━━━━━━ 27/27 8.2it/s 3.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.3it/s 0.3s
                   all        183        302      0.201      0.307      0.225      0.134

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      11.6G      1.911      2.427   0.006385          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.7it/s 0.3s
                   all        183        302      0.423      0.385      0.374      0.215

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      11.6G      1.889      2.243   0.006929          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.9it/s 0.3s
                   all        183        302      0.442      0.352      0.329      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      11.7G      1.977      2.127   0.007613          5        640: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.3it/s 0.3s
                   all        183        302      0.334      0.328      0.248      0.139

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      11.7G       2.01      2.106   0.007658          5        640: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.9it/s 0.3s
                   all        183        302      0.378       0.42      0.258      0.114

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      11.8G      1.945      2.008   0.007491          5        640: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.9it/s 0.3s
                   all        183        302      0.503       0.48      0.423      0.234

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      11.8G      1.882       2.02   0.006841          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.9it/s 0.3s
                   all        183        302       0.46      0.468      0.405      0.237

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      11.8G        1.9      1.936   0.006795          5        640: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.8it/s 0.3s
                   all        183        302      0.454      0.467      0.402      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      11.9G      1.863      1.937   0.006597          5        640: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302      0.464      0.428      0.384      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      11.9G      1.865      1.905   0.007021          5        640: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.7it/s 0.3s
                   all        183        302      0.454      0.525      0.473      0.269

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100        12G       1.81      1.788   0.006278          5        640: 100% ━━━━━━━━━━━━ 27/27 2.4it/s 11.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302       0.44       0.44      0.348      0.199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100        12G      1.812      1.813   0.006389          5        640: 100% ━━━━━━━━━━━━ 27/27 3.9it/s 7.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302      0.541      0.505       0.48      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      12.1G      1.814      1.736   0.006191          5        640: 100% ━━━━━━━━━━━━ 27/27 2.8it/s 9.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302      0.654      0.542      0.558      0.335

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      12.1G      1.796      1.665   0.006063          5        640: 100% ━━━━━━━━━━━━ 27/27 3.6it/s 7.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all        183        302      0.664      0.582      0.611      0.363

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      12.2G      1.742      1.676   0.006008          5        640: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 12.0it/s 0.3s
                   all        183        302      0.597       0.51      0.531       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      12.2G      1.747      1.628    0.00593          5        640: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.3it/s 0.3s
                   all        183        302      0.542      0.576      0.486      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      12.3G       1.79      1.621   0.006362          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.9it/s 0.3s
                   all        183        302      0.508      0.589       0.55      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      12.3G      1.794       1.67   0.006279          5        640: 100% ━━━━━━━━━━━━ 27/27 3.9it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.4it/s 0.3s
                   all        183        302       0.73      0.538       0.61      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      12.4G      1.714      1.554   0.006036          5        640: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all        183        302      0.653      0.529      0.589      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      12.4G      1.712      1.534   0.005928          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.2it/s 0.3s
                   all        183        302      0.643      0.569      0.606      0.371

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      12.5G      1.716      1.579   0.005936          5        640: 100% ━━━━━━━━━━━━ 27/27 3.6it/s 7.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all        183        302      0.604      0.624      0.602      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      12.5G      1.726      1.556   0.006072          5        640: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all        183        302      0.585      0.511      0.532      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      12.6G      1.707      1.525   0.005832          5        640: 100% ━━━━━━━━━━━━ 27/27 2.0it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.7it/s 0.3s
                   all        183        302       0.66      0.537      0.585      0.363

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      12.6G      1.675      1.534   0.005603          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 8.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.9it/s 0.3s
                   all        183        302      0.723      0.612      0.636      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      12.7G      1.618      1.392   0.005526          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302      0.571      0.542      0.543      0.339

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      12.7G      1.609      1.455   0.005798          5        640: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.2it/s 0.3s
                   all        183        302      0.684      0.552      0.595      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      12.8G      1.646      1.465   0.005871          5        640: 100% ━━━━━━━━━━━━ 27/27 3.9it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.2it/s 0.3s
                   all        183        302      0.617      0.591      0.612      0.369

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      12.8G      1.692      1.504   0.005888          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.0it/s 0.3s
                   all        183        302       0.65      0.597      0.631      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      12.9G      1.669      1.451   0.005362          5        640: 100% ━━━━━━━━━━━━ 27/27 2.7it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all        183        302      0.649      0.615      0.592      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      12.9G      1.597      1.337   0.005115          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.2it/s 0.3s
                   all        183        302      0.794      0.551      0.633      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100        13G      1.629        1.4   0.005823          5        640: 100% ━━━━━━━━━━━━ 27/27 1.8it/s 14.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s

In [17]:
import pandas as pd
from pathlib import Path

run_dir = Path("/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640")
csv_path = run_dir / "results.csv"

df = pd.read_csv(csv_path)
df.columns = [c.strip() for c in df.columns]

print("Columns:")
print(df.columns.tolist())

metric_col = "metrics/mAP50-95(B)"
best_idx = df[metric_col].idxmax()
best_row = df.loc[best_idx]

print("\nBEST BY mAP50-95:")
print("epoch:", int(best_row["epoch"]))
print("precision:", float(best_row["metrics/precision(B)"]))
print("recall:", float(best_row["metrics/recall(B)"]))
print("mAP50:", float(best_row["metrics/mAP50(B)"]))
print("mAP50-95:", float(best_row["metrics/mAP50-95(B)"]))

print("\nLAST EPOCH:")
last = df.iloc[-1]
print("epoch:", int(last["epoch"]))
print("precision:", float(last["metrics/precision(B)"]))
print("recall:", float(last["metrics/recall(B)"]))
print("mAP50:", float(last["metrics/mAP50(B)"]))
print("mAP50-95:", float(last["metrics/mAP50-95(B)"]))

print("\nWEIGHTS:")
print("best:", run_dir / "weights" / "best.pt")
print("last:", run_dir / "weights" / "last.pt")

Columns:
['epoch', 'time', 'train/box_loss', 'train/cls_loss', 'train/dfl_loss', 'metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)', 'metrics/mAP50-95(B)', 'val/box_loss', 'val/cls_loss', 'val/dfl_loss', 'lr/pg0', 'lr/pg1', 'lr/pg2']

BEST BY mAP50-95:
epoch: 71
precision: 0.82493
recall: 0.66468
mAP50: 0.76095
mAP50-95: 0.54024

LAST EPOCH:
epoch: 100
precision: 0.80521
recall: 0.64634
mAP50: 0.72757
mAP50-95: 0.51764

WEIGHTS:
best: /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/best.pt
last: /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/last.pt

In [16]:
!pip install -q pandas

In [18]:
from ultralytics import YOLO
from pathlib import Path

PROJECT = Path("/workspace/uavape_v4_model_benchmark")
RUN = {"model": "yolo26s.pt", "imgsz": 960}

model = YOLO(RUN["model"])

results = model.train(
    data=str(yaml_path),
    project=str(PROJECT / "runs"),
    name=f'v4_{Path(RUN["model"]).stem}_img{RUN["imgsz"]}',
    imgsz=RUN["imgsz"],
    epochs=100,
    batch=32,
    device=0,
    workers=8,
    seed=42,
    deterministic=True,
    cos_lr=True,
    patience=100,
    exist_ok=True,
    plots=True,
)

New https://pypi.org/project/ultralytics/8.4.63 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=960, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_yolo26s_img960, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    933412  ultralytics.nn.modules.head.Detect           [2, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,949,412 parameters, 9,949,412 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 1.3±0.3 ms, read: 1098.7±280.3 MB/s, size: 8943.8 KB)

val: Fast image access ✅ (ping: 1.4±0.9 ms, read: 263.2±139.9 MB/s, size: 3399.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/labels.jpg...
Image sizes 960 train, 960 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100        22G      1.476       22.5   0.005421          5        960: 100% ━━━━━━━━━━━━ 27/27 1.3s/it 33.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.6s/it 7.8s
                   all        183        302      0.357      0.198      0.191      0.138

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      27.2G      1.613      4.772   0.006103          5        960: 100% ━━━━━━━━━━━━ 27/27 4.6it/s 5.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.2it/s 0.4s
                   all        183        302      0.238       0.34      0.203      0.118

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      27.2G      1.706       2.64   0.005766          5        960: 100% ━━━━━━━━━━━━ 27/27 3.9it/s 6.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6it/s 0.5s
                   all        183        302      0.452      0.356      0.314      0.168

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      27.3G      1.725       2.32   0.006358          5        960: 100% ━━━━━━━━━━━━ 27/27 2.6it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.356      0.395      0.299       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      27.3G      1.758      2.163   0.006841          5        960: 100% ━━━━━━━━━━━━ 27/27 2.0it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s
                   all        183        302      0.514      0.378       0.37      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      27.3G      1.776      2.156   0.006888          5        960: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s
                   all        183        302      0.286      0.435      0.238      0.121

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      27.4G      1.761       2.02   0.007016          5        960: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s
                   all        183        302      0.405      0.237      0.222      0.113

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      27.4G      1.724      2.047    0.00648          5        960: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s
                   all        183        302      0.449      0.452      0.424      0.269

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      27.4G      1.722      1.914   0.006117          5        960: 100% ━━━━━━━━━━━━ 27/27 2.4it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.441      0.431      0.382      0.232

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      27.4G      1.676      1.887   0.006206          5        960: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s
                   all        183        302      0.636      0.473      0.494      0.308

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      27.4G      1.667      1.823   0.006517          5        960: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302        0.5      0.422      0.408       0.23

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      27.4G      1.633      1.747   0.005833          5        960: 100% ━━━━━━━━━━━━ 27/27 2.0it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s
                   all        183        302      0.593      0.492       0.53      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      27.4G      1.591      1.775   0.005729          5        960: 100% ━━━━━━━━━━━━ 27/27 3.8it/s 7.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.678      0.494      0.562      0.362

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      27.4G       1.61      1.695   0.005698          5        960: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.4it/s 0.4s
                   all        183        302      0.583      0.538      0.552      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      27.4G      1.593      1.616   0.005583          5        960: 100% ━━━━━━━━━━━━ 27/27 4.0it/s 6.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.5it/s 0.4s
                   all        183        302      0.547      0.566      0.539      0.334

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      27.4G      1.566      1.673   0.005638          5        960: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s
                   all        183        302      0.708      0.517      0.592      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      27.4G       1.51      1.559   0.005316          5        960: 100% ━━━━━━━━━━━━ 27/27 2.4it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.626      0.505      0.546       0.35

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      27.4G      1.548       1.61   0.005539          5        960: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s
                   all        183        302      0.649      0.513       0.59      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      27.4G      1.621      1.639   0.005921          5        960: 100% ━━━━━━━━━━━━ 27/27 3.8it/s 7.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.1it/s 0.4s
                   all        183        302      0.565      0.594      0.577      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      27.4G      1.533      1.525   0.005705          5        960: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.7it/s 0.4s
                   all        183        302      0.694      0.567        0.6      0.383

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      27.4G      1.502      1.492   0.005451          5        960: 100% ━━━━━━━━━━━━ 27/27 2.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s
                   all        183        302      0.625       0.57      0.603      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      27.5G      1.496      1.545   0.005271          5        960: 100% ━━━━━━━━━━━━ 27/27 2.5it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.573      0.562      0.569      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      27.5G       1.52      1.532   0.005532          5        960: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s
                   all        183        302       0.64      0.564      0.594        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      27.5G      1.495       1.52   0.005253          5        960: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 8.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.4it/s 0.4s
                   all        183        302      0.551      0.532      0.485      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      27.5G       1.51      1.522   0.005257          5        960: 100% ━━━━━━━━━━━━ 27/27 2.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.609      0.659      0.623       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      27.5G      1.405      1.316   0.004929          5        960: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.756      0.614      0.678      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      27.5G      1.423      1.396   0.005249          5        960: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.3it/s 0.4s
                   all        183        302      0.705      0.513      0.597      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      27.5G      1.452      1.465   0.005287          5        960: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.7it/s 0.3s
                   all        183        302       0.67      0.576      0.627       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      27.5G      1.483      1.526   0.005425          5        960: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.0it/s 0.4s
                   all        183        302      0.718      0.686      0.703       0.47

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      27.5G      1.462      1.406   0.004925          5        960: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s
                   all        183        302      0.688      0.505      0.564      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      27.5G        1.4      1.349   0.004662          5        960: 100% ━━━━━━━━━━━━ 27/27 2.7it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.731      0.631      0.671      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      27.5G      1.409      1.381   0.005149          5        960: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.8it/s 0.4s
                   all        183        302       0.69      0.604      0.641      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      27.5G      1.403      1.408   0.005081          5        960: 100% ━━━━━━━━━━━━ 27/27 2.8it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302       0.74      0.658       0.68      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      27.5G      1.396      1.336   0.005078          5        960: 100% ━━━━━━━━━━━━ 27/27 3.8it/s 7.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.9it/s 0.4s
                   all        183        302      0.677      0.592      0.614      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      27.5G      1.407      1.309   0.004989          5        960: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s
                   all        183        302      0.685      0.675      0.667      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

In [19]:
from ultralytics import YOLO
from pathlib import Path

PROJECT = Path("/workspace/uavape_v4_model_benchmark")
RUN = {"model": "yolo26s.pt", "imgsz": 1280}

model = YOLO(RUN["model"])

results = model.train(
    data=str(yaml_path),
    project=str(PROJECT / "runs"),
    name=f'v4_{Path(RUN["model"]).stem}_img{RUN["imgsz"]}',
    imgsz=RUN["imgsz"],
    epochs=100,
    batch=16,
    device=0,
    workers=8,
    seed=42,
    deterministic=True,
    cos_lr=True,
    patience=100,
    exist_ok=True,
    plots=True,
)

New https://pypi.org/project/ultralytics/8.4.63 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1280, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_yolo26s_img1280, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    933412  ultralytics.nn.modules.head.Detect           [2, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,949,412 parameters, 9,949,412 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.2±0.0 ms, read: 2198.5±1183.3 MB/s, size: 8943.8 KB)

val: Fast image access ✅ (ping: 0.2±0.0 ms, read: 704.9±196.1 MB/s, size: 3399.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/labels.jpg...
Image sizes 1280 train, 1280 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      19.9G      1.476      27.71    0.00574          5       1280: 100% ━━━━━━━━━━━━ 53/53 1.9it/s 28.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.0s/it 6.2s
                   all        183        302      0.235       0.25      0.184      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      25.9G      1.684       4.45   0.006076          5       1280: 100% ━━━━━━━━━━━━ 53/53 5.4it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.315       0.28      0.216      0.128

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      25.9G      1.764      2.805    0.00659          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.1it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.8it/s 0.6s
                   all        183        302      0.328       0.38      0.273       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100        26G      1.738      2.484   0.006576          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.5it/s 15.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.329      0.415        0.3      0.191

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100        26G      1.762      2.306   0.006607          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.9it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.1it/s 0.7s
                   all        183        302      0.471      0.425      0.399      0.252

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100        26G      1.696      2.184     0.0063          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.5it/s 0.6s
                   all        183        302      0.512      0.489      0.462      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      26.1G      1.693       2.17   0.006244          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.559      0.458      0.451      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      26.1G      1.672      2.081    0.00603          5       1280: 100% ━━━━━━━━━━━━ 53/53 5.2it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.529      0.403      0.445      0.281

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      26.1G      1.694      2.066   0.006257          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.442      0.483      0.432      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      26.1G      1.579      1.912   0.006023          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.8it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.537      0.485      0.506      0.308

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      26.1G      1.613      1.931   0.006133          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.4it/s 0.7s
                   all        183        302      0.538      0.473      0.494      0.327

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      26.1G      1.549      1.874   0.005927          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.569      0.532      0.567      0.364

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      26.1G      1.556      1.785   0.005738          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.629      0.566      0.586      0.394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      26.1G      1.511      1.757   0.005578          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.5it/s 0.6s
                   all        183        302      0.637      0.471      0.511      0.327

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      26.1G      1.501      1.768   0.005721          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.2it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.568      0.607      0.595      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      26.1G      1.532       1.76   0.005706          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.7it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.1it/s 0.6s
                   all        183        302      0.682      0.567      0.587      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      26.1G      1.446      1.579   0.005087          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.605       0.62       0.64      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      26.1G      1.452      1.605   0.005695          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.614       0.45      0.528      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      26.1G      1.513      1.707   0.005571          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.5it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.3it/s 0.6s
                   all        183        302      0.741      0.555       0.64      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      26.1G      1.449      1.671   0.005576          5       1280: 100% ━━━━━━━━━━━━ 53/53 5.0it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.639      0.503      0.584      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      26.1G      1.476      1.681   0.005401          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.757      0.602      0.654      0.438

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      26.1G      1.428      1.588   0.005164          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.7it/s 11.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.642       0.64      0.653      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      26.1G       1.44       1.67   0.005375          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.2it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.652      0.612      0.671      0.454

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      26.1G      1.371      1.446   0.005068          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.8it/s 0.6s
                   all        183        302      0.618      0.576      0.617      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      26.1G      1.422       1.54   0.005005          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.674      0.642      0.663      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      26.1G      1.376      1.516   0.005239          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.7it/s 11.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.7it/s 0.6s
                   all        183        302       0.73      0.529      0.618      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      26.1G      1.392      1.486     0.0053          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.758      0.564      0.637      0.428

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      26.1G      1.367      1.463   0.005173          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.6it/s 11.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.651      0.574      0.603      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      26.1G      1.376      1.491   0.005101          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.813      0.622      0.702      0.491

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      26.1G      1.359      1.401   0.004926          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.651      0.624      0.653      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      26.1G      1.328      1.395   0.005026          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.4it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.704      0.656      0.681       0.47

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      26.1G      1.306      1.422   0.004838          5       1280: 100% ━━━━━━━━━━━━ 53/53 5.2it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.5it/s 0.6s
                   all        183        302      0.686      0.656      0.677       0.47

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      26.1G      1.316       1.39   0.004615          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.1it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.715      0.586      0.651      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      26.1G      1.287      1.329   0.004574          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.7it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.727      0.579      0.666      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      26.1G      1.304      1.384   0.004727          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.749      0.594      0.663      0.461


In [20]:
from ultralytics import YOLO
from pathlib import Path

PROJECT = Path("/workspace/uavape_v4_model_benchmark")

runs = [
    {"name": "v4_yolo26s_img640", "imgsz": 640},
    {"name": "v4_yolo26s_img960", "imgsz": 960},
    {"name": "v4_yolo26s_img1280", "imgsz": 1280},
]

for run in runs:
    run_dir = PROJECT / "runs" / run["name"]
    best_pt = run_dir / "weights" / "best.pt"

    print("\n" + "=" * 80)
    print(run["name"])
    print("=" * 80)

    model = YOLO(str(best_pt))

    metrics = model.val(
        data=str(yaml_path),
        split="val",
        imgsz=run["imgsz"],
        device=0,
        plots=False,
        verbose=False,
    )

    for class_id, class_name in metrics.names.items():
        p, r, ap50, ap5095 = metrics.box.class_result(class_id)
        print(
            f"{class_id} {class_name}: "
            f"P={p:.5f}, R={r:.5f}, AP50={ap50:.5f}, AP50-95={ap5095:.5f}"
        )

    print(
        "aggregate:",
        f"P={metrics.box.mp:.5f},",
        f"R={metrics.box.mr:.5f},",
        f"mAP50={metrics.box.map50:.5f},",
        f"mAP50-95={metrics.box.map:.5f}",
    )

================================================================================
v4_yolo26s_img640
================================================================================
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 0.3±0.2 ms, read: 1718.3±627.8 MB/s, size: 5754.2 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.7it/s 7.0s
                   all        183        302      0.812      0.669      0.762      0.542
Speed: 0.5ms preprocess, 2.8ms inference, 0.0ms loss, 0.1ms postprocess per image
0 vape: P=0.88375, R=0.73762, AP50=0.87651, AP50-95=0.64776
1 lighter: P=0.74003, R=0.60000, AP50=0.64725, AP50-95=0.43683
aggregate: P=0.81189, R=0.66881, mAP50=0.76188, mAP50-95=0.54229

================================================================================
v4_yolo26s_img960
================================================================================
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 0.6±0.4 ms, read: 669.6±391.8 MB/s, size: 4319.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.5it/s 8.3s
                   all        183        302      0.823      0.696       0.74      0.548
Speed: 1.1ms preprocess, 3.3ms inference, 0.0ms loss, 0.1ms postprocess per image
0 vape: P=0.89150, R=0.77282, AP50=0.85692, AP50-95=0.68355
1 lighter: P=0.75517, R=0.62000, AP50=0.62225, AP50-95=0.41171
aggregate: P=0.82333, R=0.69641, mAP50=0.73958, mAP50-95=0.54763

================================================================================
v4_yolo26s_img1280
================================================================================
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 0.6±0.3 ms, read: 1234.8±930.1 MB/s, size: 9446.7 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.4it/s 8.8s
                   all        183        302      0.839      0.749      0.803      0.602
Speed: 1.9ms preprocess, 3.6ms inference, 0.0ms loss, 0.1ms postprocess per image
0 vape: P=0.90879, R=0.83851, AP50=0.91763, AP50-95=0.70669
1 lighter: P=0.76984, R=0.66000, AP50=0.68792, AP50-95=0.49768
aggregate: P=0.83932, R=0.74926, mAP50=0.80278, mAP50-95=0.60219

In [25]:
print(yaml_path)
print(yaml_path.exists())
print(yaml_path.read_text())

/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml
True
path: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610
train: images/train
val: images/val
test: images/test
nc: 2
names:
  0: vape
  1: lighter

In [22]:
from pathlib import Path

for p in Path("/workspace").iterdir():
    if p.is_file():
        print(p.name, round(p.stat().st_size / 1024**3, 3), "GB")
    else:
        print(p.name, "DIR")

yolo11s.pt 0.018 GB
runs DIR
yolo26n.pt 0.005 GB
yolo26s.pt 0.019 GB
v4_real_final_20260610_yolo_export.tar.gz 3.054 GB
uavape_v4_model_benchmark DIR
.cache DIR
.ipynb_checkpoints DIR
Untitled.ipynb 0.0 GB

In [23]:
!rm /workspace/v4_real_final_20260610_yolo_export.tar.gz

In [24]:
from pathlib import Path

for p in Path("/workspace").iterdir():
    if p.is_file():
        print(p.name, round(p.stat().st_size / 1024**3, 3), "GB")
    else:
        print(p.name, "DIR")

v4_real_final_20260610_yolo_export.tar.gz 0.004 GB
yolo11s.pt 0.018 GB
runs DIR
yolo26n.pt 0.005 GB
yolo26s.pt 0.019 GB
uavape_v4_model_benchmark DIR
.cache DIR
.ipynb_checkpoints DIR
Untitled.ipynb 0.0 GB

In [26]:
from ultralytics import YOLO
from pathlib import Path
import gc
import torch

PROJECT = Path("/workspace/uavape_v4_model_benchmark")

RUN_QUEUE = [
    # Stable modern comparator, feasible sizes
    {"model": "yolo11s.pt", "imgsz": 640, "batch": 32},
    {"model": "yolo11s.pt", "imgsz": 960, "batch": 32},

    # Literature-anchor comparator, feasible sizes
    {"model": "yolov8s.pt", "imgsz": 640, "batch": 32},
    {"model": "yolov8s.pt", "imgsz": 960, "batch": 32},

    # Capacity check at deployment-feasible input
    {"model": "yolo26m.pt", "imgsz": 640, "batch": 32},
    {"model": "yolo11m.pt", "imgsz": 640, "batch": 32},
    {"model": "yolov8m.pt", "imgsz": 640, "batch": 32},

    # Upper-resolution checks last
    {"model": "yolo11s.pt", "imgsz": 1280, "batch": 16},
    {"model": "yolov8s.pt", "imgsz": 1280, "batch": 16},
]

completed = []

for run in RUN_QUEUE:
    model_name = run["model"]
    imgsz = run["imgsz"]
    batch = run["batch"]
    run_name = f"v4_{Path(model_name).stem}_img{imgsz}"
    run_dir = PROJECT / "runs" / run_name

    if (run_dir / "weights" / "best.pt").exists():
        print(f"Skipping existing run: {run_name}")
        completed.append(run_name)
        continue

    print("\n" + "=" * 80)
    print(f"Training {run_name} | batch={batch}")
    print("=" * 80)

    try:
        model = YOLO(model_name)
        model.train(
            data=str(yaml_path),
            project=str(PROJECT / "runs"),
            name=run_name,
            imgsz=imgsz,
            epochs=100,
            batch=batch,
            device=0,
            workers=8,
            seed=42,
            deterministic=True,
            cos_lr=True,
            patience=100,
            exist_ok=True,
            plots=True,
        )
        completed.append(run_name)

    except RuntimeError as e:
        print(f"Run failed: {run_name}")
        print(e)
        if "out of memory" in str(e).lower():
            print("OOM detected. Rerun manually with lower batch.")
        break

    finally:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

print("Completed:", completed)

================================================================================
Training v4_yolo11s_img640 | batch=32
================================================================================
New https://pypi.org/project/ultralytics/8.4.63 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_yolo11s_img640, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    820182  ultralytics.nn.modules.head.Detect           [2, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,428,566 parameters, 9,428,550 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.2±0.0 ms, read: 3111.7±416.3 MB/s, size: 8943.8 KB)

val: Fast image access ✅ (ping: 0.2±0.0 ms, read: 632.7±194.8 MB/s, size: 3399.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      7.93G      1.509      4.827       1.29          5        640: 100% ━━━━━━━━━━━━ 27/27 1.4it/s 19.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.9it/s 0.8s
                   all        183        302      0.148       0.33      0.118     0.0613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      10.4G      1.704      2.229      1.374          5        640: 100% ━━━━━━━━━━━━ 27/27 2.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s
                   all        183        302     0.0282       0.35     0.0129    0.00522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      10.4G      1.735      2.013       1.34          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s
                   all        183        302     0.0012      0.139   0.000187   0.000103

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      10.4G      1.731      1.943      1.343          5        640: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s
                   all        183        302   0.000951      0.112   0.000186   7.35e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      10.4G      1.853      2.048      1.465          5        640: 100% ━━━━━━━━━━━━ 27/27 3.7it/s 7.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4it/s 0.5s
                   all        183        302    0.00258     0.0547   0.000185   5.29e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      10.5G      1.917          2      1.486          5        640: 100% ━━━━━━━━━━━━ 27/27 3.7it/s 7.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s
                   all        183        302      0.229       0.13     0.0634     0.0292

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      10.5G       1.81      1.941      1.445          5        640: 100% ━━━━━━━━━━━━ 27/27 2.8it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.5it/s 0.5s
                   all        183        302      0.221      0.308       0.13     0.0639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      10.5G      1.712      1.915      1.391          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.7it/s 0.4s
                   all        183        302      0.399      0.471      0.372      0.208

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      10.5G      1.735      1.815      1.388          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 8.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.7it/s 0.4s
                   all        183        302      0.377      0.455       0.35      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      10.5G      1.729      1.814      1.376          5        640: 100% ━━━━━━━━━━━━ 27/27 2.7it/s 10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s
                   all        183        302      0.299      0.257       0.28      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      10.5G      1.716      1.801      1.396          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.1it/s 0.4s
                   all        183        302      0.567      0.383       0.44      0.254

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      10.5G      1.654      1.662      1.339          5        640: 100% ━━━━━━━━━━━━ 27/27 4.3it/s 6.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.5it/s 0.4s
                   all        183        302      0.322      0.367      0.283      0.161

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      10.5G      1.615      1.724      1.315          5        640: 100% ━━━━━━━━━━━━ 27/27 3.3it/s 8.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 9.7it/s 0.3s
                   all        183        302      0.494      0.423      0.365      0.223

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      10.5G      1.538      1.611      1.292          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s
                   all        183        302      0.509      0.471      0.433       0.25

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      10.5G      1.576       1.56      1.286          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 10.7it/s 0.3s
                   all        183        302      0.536      0.478      0.465      0.271

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      10.5G      1.501      1.544      1.269          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.6it/s 0.4s
                   all        183        302      0.513       0.45      0.449       0.28

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      10.5G      1.514      1.519      1.269          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s
                   all        183        302      0.663      0.455      0.493      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      10.5G      1.551      1.549       1.31          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.7it/s 0.4s
                   all        183        302      0.555      0.482      0.442       0.27

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      10.5G      1.551      1.523      1.281          5        640: 100% ━━━━━━━━━━━━ 27/27 3.9it/s 7.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s
                   all        183        302      0.515      0.525      0.491      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      10.5G      1.447       1.39      1.236          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.2it/s 0.4s
                   all        183        302       0.64      0.535      0.558      0.341

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      10.5G      1.506      1.406      1.265          5        640: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s
                   all        183        302      0.613       0.53      0.585      0.349

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      10.5G      1.508       1.46      1.266          5        640: 100% ━━━━━━━━━━━━ 27/27 3.4it/s 8.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 7.8it/s 0.4s
                   all        183        302      0.571      0.507      0.508      0.308

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      10.5G      1.503      1.448      1.293          5        640: 100% ━━━━━━━━━━━━ 27/27 2.7it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.2it/s 0.4s
                   all        183        302       0.58      0.445      0.491       0.31

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      10.5G      1.396      1.341      1.205          5        640: 100% ━━━━━━━━━━━━ 27/27 3.6it/s 7.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s
                   all        183        302      0.582      0.578      0.544      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      10.5G      1.435      1.368      1.221          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.3it/s 0.4s
                   all        183        302      0.554      0.582      0.525      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      10.5G      1.362      1.258      1.199          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s
                   all        183        302      0.528      0.604      0.547       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      10.5G      1.349      1.299      1.202          5        640: 100% ━━━━━━━━━━━━ 27/27 3.2it/s 8.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.1it/s 0.4s
                   all        183        302      0.637      0.556      0.598      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      10.5G      1.365      1.334      1.218          5        640: 100% ━━━━━━━━━━━━ 27/27 4.2it/s 6.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.5it/s 0.3s
                   all        183        302      0.628      0.539      0.562      0.343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      10.5G      1.458      1.361      1.234          5        640: 100% ━━━━━━━━━━━━ 27/27 2.9it/s 9.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 10.7it/s 0.3s
                   all        183        302      0.661      0.525       0.55      0.359

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      10.5G      1.383      1.279      1.199          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.0it/s 0.4s
                   all        183        302      0.674      0.512      0.583      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      10.5G      1.328      1.213       1.16          5        640: 100% ━━━━━━━━━━━━ 27/27 3.1it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.2it/s 0.4s
                   all        183        302      0.681      0.556       0.59      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      10.5G       1.38      1.259      1.207          5        640: 100% ━━━━━━━━━━━━ 27/27 1.9it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 10.9it/s 0.3s
                   all        183        302      0.559      0.634       0.62      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      10.5G      1.383      1.282      1.228          5        640: 100% ━━━━━━━━━━━━ 27/27 3.5it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 11.2it/s 0.3s
                   all        183        302      0.706      0.617      0.648      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      10.5G      1.324      1.239      1.198          5        640: 100% ━━━━━━━━━━━━ 27/27 3.0it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 8.2it/s 0.4s
                   all        183        302      0.588      0.592       0.57      0.369

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      10.5G      1.313       1.18      1.169          5        640: 100% ━━━━━━━━━━━━ 27/27 4.3it/s 6.3s

In [28]:
!find runs -path "*/weights/best.pt" -o -path "*/results.csv" -o -path "*/args.yaml" | sort

In [29]:
from pathlib import Path
import pandas as pd

for csv in sorted(Path("runs").rglob("results.csv")):
    run = csv.parent
    try:
        df = pd.read_csv(csv)
        df.columns = [c.strip() for c in df.columns]

        last_epoch = int(df["epoch"].iloc[-1])
        metric_cols = [c for c in df.columns if "metrics/" in c]

        candidates = [c for c in metric_cols if "mAP50-95" in c]
        best_idx = df[candidates[0]].idxmax() if candidates else len(df) - 1

        best = df.loc[best_idx]

        print("\n" + "="*80)
        print(run)
        print(f"epochs completed: {last_epoch + 1}")
        print(f"best epoch: {int(best['epoch'])}")

        for c in metric_cols:
            print(f"{c}: {best[c]:.5f}")

        print("best.pt:", (run / "weights" / "best.pt").exists())
        print("last.pt:", (run / "weights" / "last.pt").exists())

    except Exception as e:
        print("\nFAILED TO READ:", csv, e)

In [30]:
from pathlib import Path
import pandas as pd

# Try common run locations
roots = [
    Path("runs"),
    Path("/content/runs"),
    Path("/workspace/runs"),
    Path.cwd() / "runs",
]

existing_roots = [p for p in roots if p.exists()]
print("Current folder:", Path.cwd())
print("Existing run folders:", existing_roots)

if not existing_roots:
    print("No runs folder found. Show folders in current directory:")
    print([p.name for p in Path.cwd().iterdir() if p.is_dir()])

Current folder: /workspace
Existing run folders: [PosixPath('runs'), PosixPath('/workspace/runs'), PosixPath('/workspace/runs')]

In [31]:
from pathlib import Path
import pandas as pd

root = existing_roots[0] if existing_roots else Path.cwd()
csvs = sorted(root.rglob("results.csv"))

print(f"Found {len(csvs)} results.csv files under {root}")

for csv in csvs:
    run = csv.parent
    df = pd.read_csv(csv)
    df.columns = [c.strip() for c in df.columns]

    print("\n" + "=" * 90)
    print("RUN:", run)
    print("ROWS:", len(df))
    
    if "epoch" in df.columns:
        print("EPOCHS COMPLETED:", int(df["epoch"].iloc[-1]) + 1)

    print("HAS best.pt:", (run / "weights" / "best.pt").exists())
    print("HAS last.pt:", (run / "weights" / "last.pt").exists())

    metric_cols = [c for c in df.columns if c.startswith("metrics/")]
    print("METRIC COLUMNS:", metric_cols)

    map_cols = [c for c in metric_cols if "mAP50-95" in c]
    if map_cols:
        best_idx = df[map_cols[0]].idxmax()
    else:
        best_idx = len(df) - 1

    best = df.iloc[best_idx]
    print("BEST ROW INDEX:", best_idx)

    for c in metric_cols:
        try:
            print(f"{c}: {float(best[c]):.5f}")
        except:
            print(f"{c}: {best[c]}")

Found 0 results.csv files under runs

In [32]:
from pathlib import Path

for p in Path.cwd().rglob("*"):
    if p.name in ["results.csv", "best.pt", "last.pt", "args.yaml"]:
        print(p)

/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img1280/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img1280/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8m_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11m_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26m_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img960/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img960/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/results.csv
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img1280/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img1280/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img1280/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img1280/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8m_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8m_img640/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11m_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11m_img640/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26m_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26m_img640/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img960/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img960/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img640/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/weights/last.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/best.pt
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/last.pt

In [33]:
from pathlib import Path
import pandas as pd

root = Path("/workspace/uavape_v4_model_benchmark/runs")
csvs = sorted(root.rglob("results.csv"))

rows = []

for csv in csvs:
    run_dir = csv.parent
    name = run_dir.name

    df = pd.read_csv(csv)
    df.columns = [c.strip() for c in df.columns]

    # Find mAP50-95 column
    map95_cols = [c for c in df.columns if "mAP50-95" in c]
    map50_cols = [c for c in df.columns if "mAP50(B)" in c or "mAP50" in c and "95" not in c]
    precision_cols = [c for c in df.columns if "precision" in c]
    recall_cols = [c for c in df.columns if "recall" in c]

    if map95_cols:
        best_idx = df[map95_cols[0]].idxmax()
    else:
        best_idx = len(df) - 1

    best = df.loc[best_idx]

    rows.append({
        "run": name,
        "epochs_done": int(df["epoch"].iloc[-1]) + 1 if "epoch" in df.columns else len(df),
        "best_epoch": int(best["epoch"]) if "epoch" in df.columns else best_idx,
        "precision": float(best[precision_cols[0]]) if precision_cols else None,
        "recall": float(best[recall_cols[0]]) if recall_cols else None,
        "mAP50": float(best[map50_cols[0]]) if map50_cols else None,
        "mAP50-95": float(best[map95_cols[0]]) if map95_cols else None,
        "best_pt": (run_dir / "weights" / "best.pt").exists(),
        "last_pt": (run_dir / "weights" / "last.pt").exists(),
    })

summary = pd.DataFrame(rows).sort_values("mAP50-95", ascending=False)
summary

,run,epochs_done,best_epoch,precision,recall,mAP50,mAP50-95,best_pt,last_pt
5,v4_yolo26s_img1280,101,77,0.83866,0.74882,0.80233,0.60501,True,True
1,v4_yolo11s_img1280,101,74,0.83625,0.75079,0.78559,0.58851,True,True
3,v4_yolo11s_img960,101,89,0.82587,0.74317,0.77487,0.56639,True,True
4,v4_yolo26m_img640,101,82,0.77691,0.75584,0.79481,0.56215,True,True
7,v4_yolo26s_img960,101,90,0.82190,0.68432,0.74253,0.54957,True,True
9,v4_yolov8s_img1280,101,76,0.85542,0.66381,0.73735,0.54448,True,True
6,v4_yolo26s_img640,101,71,0.82493,0.66468,0.76095,0.54024,True,True
11,v4_yolov8s_img960,101,89,0.82325,0.67099,0.73797,0.53573,True,True
8,v4_yolov8m_img640,101,88,0.78257,0.71402,0.75316,0.53368,True,True
0,v4_yolo11m_img640,101,81,0.86303,0.68856,0.75816,0.52415,True,True
2,v4_yolo11s_img640,101,87,0.79727,0.69695,0.74736,0.50696,True,True
10,v4_yolov8s_img640,101,69,0.77860,0.68419,0.71935,0.48731,True,True

In [35]:
from pathlib import Path

root = Path("/workspace/uavape_v4_model_benchmark")

yamls = sorted(list(root.rglob("*.yaml")) + list(root.rglob("*.yml")))

for y in yamls:
    print(y)

/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8m_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img1280/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img640/args.yaml
/workspace/uavape_v4_model_benchmark/runs/v4_yolov8s_img960/args.yaml

In [36]:
for y in yamls:
    txt = y.read_text(errors="ignore")
    if "train:" in txt and "val:" in txt and "names:" in txt:
        print("\n" + "="*80)
        print(y)
        print(txt[:1000])

================================================================================
/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml
path: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610
train: images/train
val: images/val
test: images/test
nc: 2
names:
  0: vape
  1: lighter

In [37]:
data_yaml = "/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml"

In [38]:
from pathlib import Path
from ultralytics import YOLO
import pandas as pd

runs = Path("/workspace/uavape_v4_model_benchmark/runs")
data_yaml = "/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml"

rows = []

for best in sorted(runs.rglob("weights/best.pt")):
    run_name = best.parents[1].name
    print("Validating:", run_name)

    model = YOLO(str(best))
    metrics = model.val(
        data=data_yaml,
        split="val",
        plots=False,
        save_json=False,
        verbose=False
    )

    names = metrics.names
    ap50 = metrics.box.ap50
    ap = metrics.box.ap
    p = metrics.box.p
    r = metrics.box.r

    for i, cls_name in names.items():
        rows.append({
            "run": run_name,
            "class": cls_name,
            "precision": float(p[i]),
            "recall": float(r[i]),
            "AP50": float(ap50[i]),
            "AP50-95": float(ap[i]),
        })

per_class = pd.DataFrame(rows)
per_class.to_csv("/workspace/uavape_v4_model_benchmark/v4_per_class_val_summary.csv", index=False)

per_class.sort_values(["class", "AP50-95"], ascending=[True, False])

Validating: v4_yolo11m_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO11m summary (fused): 126 layers, 20,031,574 parameters, 0 gradients, 67.7 GFLOPs
val: Fast image access ✅ (ping: 0.9±0.3 ms, read: 189.0±73.1 MB/s, size: 4319.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.3it/s 9.1s
                   all        183        302      0.867      0.686      0.759      0.526
Speed: 0.5ms preprocess, 3.3ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolo11s_img1280
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO11s summary (fused): 101 layers, 9,413,574 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access ✅ (ping: 1.0±0.3 ms, read: 533.7±334.8 MB/s, size: 9446.7 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.4it/s 8.8s
                   all        183        302      0.831      0.751      0.785      0.593
Speed: 1.7ms preprocess, 2.1ms inference, 0.0ms loss, 0.4ms postprocess per image
Validating: v4_yolo11s_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO11s summary (fused): 101 layers, 9,413,574 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access ✅ (ping: 0.4±0.1 ms, read: 936.7±597.4 MB/s, size: 4583.2 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.9it/s 6.4s
                   all        183        302      0.797      0.686      0.743      0.505
Speed: 0.5ms preprocess, 1.0ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolo11s_img960
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO11s summary (fused): 101 layers, 9,413,574 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access ✅ (ping: 1.0±0.2 ms, read: 688.8±405.8 MB/s, size: 6275.7 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.9it/s 6.2s
                   all        183        302      0.828      0.734      0.775      0.567
Speed: 0.9ms preprocess, 1.4ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolo26m_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26m summary (fused): 132 layers, 20,350,994 parameters, 0 gradients, 67.9 GFLOPs
val: Fast image access ✅ (ping: 1.3±0.1 ms, read: 228.3±108.9 MB/s, size: 1499.1 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.4it/s 8.4s
                   all        183        302       0.77      0.767      0.797      0.561
Speed: 0.5ms preprocess, 1.4ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating: v4_yolo26s_img1280
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 1.2±0.6 ms, read: 471.9±266.9 MB/s, size: 1719.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.4it/s 8.3s
                   all        183        302      0.839      0.749      0.803      0.602
Speed: 1.9ms preprocess, 2.0ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating: v4_yolo26s_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 0.8±0.4 ms, read: 443.3±167.0 MB/s, size: 5770.2 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 2.1it/s 5.7s
                   all        183        302      0.812      0.669      0.762      0.542
Speed: 0.5ms preprocess, 0.8ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating: v4_yolo26s_img960
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
YOLO26s summary (fused): 122 layers, 9,465,954 parameters, 0 gradients, 20.5 GFLOPs
val: Fast image access ✅ (ping: 0.5±0.3 ms, read: 775.7±381.6 MB/s, size: 4907.1 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.5it/s 7.9s
                   all        183        302      0.823      0.696       0.74      0.548
Speed: 0.9ms preprocess, 1.2ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating: v4_yolov8m_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
Model summary (fused): 93 layers, 25,840,918 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.8±0.5 ms, read: 659.0±255.2 MB/s, size: 8394.9 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.6it/s 7.5s
                   all        183        302      0.786      0.712      0.756      0.538
Speed: 0.5ms preprocess, 2.3ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolov8s_img1280
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
Model summary (fused): 73 layers, 11,126,358 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 0.2±0.1 ms, read: 1343.7±157.7 MB/s, size: 6485.7 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 2.1it/s 5.8s
                   all        183        302      0.851      0.664      0.738      0.547
Speed: 1.7ms preprocess, 2.0ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolov8s_img640
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
Model summary (fused): 73 layers, 11,126,358 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 1.2±0.1 ms, read: 320.2±183.8 MB/s, size: 3332.5 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.7it/s 6.9s
                   all        183        302      0.787      0.681      0.716      0.483
Speed: 0.5ms preprocess, 1.2ms inference, 0.0ms loss, 0.5ms postprocess per image
Validating: v4_yolov8s_img960
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
Model summary (fused): 73 layers, 11,126,358 parameters, 0 gradients, 28.4 GFLOPs
val: Fast image access ✅ (ping: 1.1±0.2 ms, read: 396.8±167.9 MB/s, size: 6103.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 12/12 1.7it/s 6.9s
                   all        183        302      0.825       0.67      0.736      0.539
Speed: 1.1ms preprocess, 1.6ms inference, 0.0ms loss, 0.5ms postprocess per image

                   run    class  precision    recall      AP50   AP50-95
3   v4_yolo11s_img1280  lighter   0.784678  0.660000  0.690710  0.508317
11  v4_yolo26s_img1280  lighter   0.769843  0.660000  0.687925  0.497680
19  v4_yolov8s_img1280  lighter   0.865730  0.590000  0.671865  0.476142
7    v4_yolo11s_img960  lighter   0.776248  0.630000  0.647348  0.457565
9    v4_yolo26m_img640  lighter   0.697677  0.690000  0.706005  0.455211
13   v4_yolo26s_img640  lighter   0.740030  0.600000  0.647245  0.436827
17   v4_yolov8m_img640  lighter   0.696642  0.620038  0.638209  0.427761
23   v4_yolov8s_img960  lighter   0.770661  0.537682  0.606621  0.418280
15   v4_yolo26s_img960  lighter   0.755171  0.620000  0.622254  0.411715
1    v4_yolo11m_img640  lighter   0.855696  0.590000  0.635734  0.403049
5    v4_yolo11s_img640  lighter   0.676415  0.580000  0.593791  0.372776
21   v4_yolov8s_img640  lighter   0.715741  0.579131  0.594110  0.370490
10  v4_yolo26s_img1280     vape   0.908788  0.838513  0.917628  0.706693
14   v4_yolo26s_img960     vape   0.891496  0.772819  0.856915  0.683555
2   v4_yolo11s_img1280     vape   0.876334  0.841940  0.879775  0.677224
6    v4_yolo11s_img960     vape   0.880421  0.838326  0.903010  0.676750
8    v4_yolo26m_img640     vape   0.841968  0.844021  0.888764  0.666034
22   v4_yolov8s_img960     vape   0.879915  0.801980  0.866328  0.658765
16   v4_yolov8m_img640     vape   0.875988  0.804294  0.873176  0.648426
0    v4_yolo11m_img640     vape   0.877632  0.782178  0.881775  0.648396
12   v4_yolo26s_img640     vape   0.883750  0.737624  0.876509  0.647757
4    v4_yolo11s_img640     vape   0.917504  0.792079  0.893169  0.637785
18  v4_yolov8s_img1280     vape   0.836963  0.737624  0.803182  0.617642
20   v4_yolov8s_img640     vape   0.858271  0.782178  0.838616  0.595690

In [39]:
from ultralytics import YOLO
from pathlib import Path

data_yaml = "/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml"
project = "/workspace/uavape_v4_model_benchmark/runs"

runs = [
    {
        "model": "yolo26n.pt",
        "imgsz": 640,
        "name": "v4_yolo26n_img640",
    },
    {
        "model": "yolo26n.pt",
        "imgsz": 960,
        "name": "v4_yolo26n_img960",
    },
    {
        "model": "yolo11n.pt",
        "imgsz": 640,
        "name": "v4_yolo11n_img640",
    },
    {
        "model": "yolo11n.pt",
        "imgsz": 960,
        "name": "v4_yolo11n_img960",
    },
]

for r in runs:
    out_dir = Path(project) / r["name"]

    if (out_dir / "weights" / "best.pt").exists():
        print(f"Skipping completed run: {r['name']}")
        continue

    print(f"\nStarting {r['name']}")

    model = YOLO(r["model"])
    model.train(
        data=data_yaml,
        epochs=100,
        imgsz=r["imgsz"],
        seed=42,
        project=project,
        name=r["name"],
        exist_ok=True,
        cos_lr=True,
        plots=True,
        verbose=True,
    )

Starting v4_yolo26n_img640
New https://pypi.org/project/ultralytics/8.4.63 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_yolo26n_img640, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs/v4_yolo26n_img640, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    241956  ultralytics.nn.modules.head.Detect           [2, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,504,580 parameters, 2,504,580 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.1±0.0 ms, read: 388.6±69.4 MB/s, size: 8943.8 KB)

val: Fast image access ✅ (ping: 0.2±0.1 ms, read: 256.5±59.8 MB/s, size: 3399.3 KB)

val: /workspace/uavape_v4_model_benchmark/datasets/v4_real_final_20260610/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26n_img640/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs/v4_yolo26n_img640
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      4.62G      1.852      7.788   0.006612          5        640: 100% ━━━━━━━━━━━━ 53/53 2.6it/s 20.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 1.1s/it 6.3s
                   all        183        302    0.00178      0.251     0.0494     0.0366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      4.63G      1.914      6.181    0.00654          5        640: 100% ━━━━━━━━━━━━ 53/53 8.1it/s 6.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 21.2it/s 0.3s
                   all        183        302      0.345      0.196      0.215      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      4.65G      1.956      4.859   0.006711          5        640: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 20.5it/s 0.3s
                   all        183        302       0.34      0.363       0.26      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      4.65G      1.915       3.99   0.006536          5        640: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 21.7it/s 0.3s
                   all        183        302      0.286      0.412      0.245      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      4.65G      1.954      3.356   0.006733          5        640: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 20.8it/s 0.3s
                   all        183        302      0.291      0.353      0.246      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      4.66G      1.936      2.879   0.006563          5        640: 100% ━━━━━━━━━━━━ 53/53 4.7it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 21.6it/s 0.3s
                   all        183        302      0.386      0.365      0.304      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      4.66G      1.965      2.679   0.006758          5        640: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 13.3it/s 0.5s
                   all        183        302      0.429      0.474      0.395      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      4.66G      1.962      2.495   0.006603          5        640: 100% ━━━━━━━━━━━━ 53/53 4.1it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.8it/s 0.4s
                   all        183        302      0.417      0.461       0.35      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      4.67G      1.891      2.295   0.006266          5        640: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.6it/s 0.4s
                   all        183        302      0.494      0.418      0.421      0.249

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      4.68G      1.847      2.161   0.006378          5        640: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.8it/s 0.4s
                   all        183        302      0.471      0.495      0.423      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      4.71G      1.901      2.233   0.006638          5        640: 100% ━━━━━━━━━━━━ 53/53 4.1it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.2it/s 0.4s
                   all        183        302      0.499        0.5      0.439      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      4.71G      1.852      2.097   0.006316          5        640: 100% ━━━━━━━━━━━━ 53/53 2.8it/s 18.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.5it/s 0.4s
                   all        183        302      0.497      0.496      0.448      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      4.71G      1.842      2.003   0.006106          5        640: 100% ━━━━━━━━━━━━ 53/53 3.5it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.0it/s 0.4s
                   all        183        302      0.475       0.46      0.433      0.266

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      4.71G      1.902      1.961   0.006503          5        640: 100% ━━━━━━━━━━━━ 53/53 3.6it/s 14.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.2it/s 0.4s
                   all        183        302      0.544      0.492      0.478      0.289

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      4.71G       1.83      1.918   0.006258          5        640: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.1it/s 0.4s
                   all        183        302      0.455      0.468      0.418      0.244

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      4.71G      1.862      1.856   0.006422          5        640: 100% ━━━━━━━━━━━━ 53/53 3.7it/s 14.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.1it/s 0.4s
                   all        183        302      0.513      0.549      0.509      0.312

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      4.71G      1.783      1.786   0.005767          5        640: 100% ━━━━━━━━━━━━ 53/53 3.6it/s 14.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.5it/s 0.4s
                   all        183        302      0.539      0.469      0.478      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      4.71G      1.724      1.733   0.006201          5        640: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 18.6it/s 0.3s
                   all        183        302      0.546        0.4      0.428      0.265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      4.71G      1.816      1.837   0.005891          5        640: 100% ━━━━━━━━━━━━ 53/53 3.5it/s 15.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.9it/s 0.4s
                   all        183        302      0.527      0.505      0.495      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      4.71G      1.775      1.754    0.00625          5        640: 100% ━━━━━━━━━━━━ 53/53 3.7it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 19.6it/s 0.3s
                   all        183        302      0.576      0.497      0.517      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      4.71G      1.796      1.746   0.005986          5        640: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 18.1it/s 0.3s
                   all        183        302      0.528      0.547      0.516      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      4.71G      1.749      1.741   0.005821          5        640: 100% ━━━━━━━━━━━━ 53/53 4.3it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.9it/s 0.4s
                   all        183        302      0.551      0.395      0.404      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      4.72G      1.752      1.761   0.005959          5        640: 100% ━━━━━━━━━━━━ 53/53 3.8it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.9it/s 0.4s
                   all        183        302      0.685      0.465      0.571       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      4.72G      1.665      1.582    0.00554          5        640: 100% ━━━━━━━━━━━━ 53/53 3.4it/s 15.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.9it/s 0.4s
                   all        183        302      0.563      0.468      0.487      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      4.72G      1.729      1.646   0.005543          5        640: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.7it/s 0.4s
                   all        183        302      0.574      0.507        0.5      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      4.72G      1.702      1.624   0.005821          5        640: 100% ━━━━━━━━━━━━ 53/53 4.2it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.6it/s 0.4s
                   all        183        302       0.59      0.537      0.534       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      4.72G      1.719       1.65   0.005795          5        640: 100% ━━━━━━━━━━━━ 53/53 3.2it/s 16.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.3it/s 0.4s
                   all        183        302      0.643      0.493      0.528      0.321

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      4.72G      1.705      1.607   0.005905          5        640: 100% ━━━━━━━━━━━━ 53/53 3.6it/s 14.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 16.0it/s 0.4s
                   all        183        302      0.565      0.534      0.522      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      4.72G      1.729      1.641   0.005801          5        640: 100% ━━━━━━━━━━━━ 53/53 4.8it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.1it/s 0.4s
                   all        183        302      0.693      0.559      0.602      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      4.72G      1.709      1.528   0.005574          5        640: 100% ━━━━━━━━━━━━ 53/53 3.1it/s 17.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 21.9it/s 0.3s
                   all        183        302       0.62      0.542       0.55      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      4.72G      1.656      1.517   0.005542          5        640: 100% ━━━━━━━━━━━━ 53/53 3.9it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.9it/s 0.4s
                   all        183        302      0.609      0.487      0.507      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      4.72G      1.678      1.575   0.005494          5        640: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.6it/s 0.4s
                   all        183        302      0.678      0.512      0.559      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      4.72G      1.656       1.47   0.005238          5        640: 100% ━━━━━━━━━━━━ 53/53 3.5it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.3it/s 0.4s
                   all        183        302      0.637      0.506      0.514      0.321

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/100      4.72G       1.65      1.469    0.00529          5        640: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 14.8it/s 0.4s
                   all        183        302      0.627      0.576      0.596      0.371

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/100      4.72G      1.627       1.48   0.005314          5        640: 100% ━━━━━━━━━━━━ 53/53 3.7it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 15.3it/s 0.4s
                   all        183        302       0.65      0.597      0.609      0.385


In [40]:
!pip install -q sahi pycocotools pyyaml tqdm

In [41]:
from pathlib import Path
from PIL import Image
from tqdm import tqdm
import json
import csv
import yaml
import contextlib
import io

from sahi import AutoDetectionModel
from sahi.predict import get_sliced_prediction
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

PROJECT = Path("/workspace/uavape_v4_model_benchmark")
DATA_DIR = PROJECT / "datasets" / "v4_real_final_20260610"
VAL_IMG_DIR = DATA_DIR / "images" / "val"
VAL_LBL_DIR = DATA_DIR / "labels" / "val"
OUT_DIR = PROJECT / "tiling_eval"
OUT_DIR.mkdir(parents=True, exist_ok=True)

CATEGORIES = [
    {"id": 1, "name": "vape"},
    {"id": 2, "name": "lighter"},
]

TILE_RUNS = [
    {
        "name": "v4_yolo26s_img640_sahi_tile1280_ov20",
        "weights": PROJECT / "runs" / "v4_yolo26s_img640" / "weights" / "best.pt",
        "model_imgsz": 640,
        "slice_size": 1280,
        "overlap": 0.20,
    },
    {
        "name": "v4_yolo26s_img960_sahi_tile1280_ov20",
        "weights": PROJECT / "runs" / "v4_yolo26s_img960" / "weights" / "best.pt",
        "model_imgsz": 960,
        "slice_size": 1280,
        "overlap": 0.20,
    },
    {
        "name": "v4_yolo11s_img960_sahi_tile1280_ov20",
        "weights": PROJECT / "runs" / "v4_yolo11s_img960" / "weights" / "best.pt",
        "model_imgsz": 960,
        "slice_size": 1280,
        "overlap": 0.20,
    },
    # Optional deployment-boundary check
    {
        "name": "v4_yolo11n_img960_sahi_tile1280_ov20",
        "weights": PROJECT / "runs" / "v4_yolo11n_img960" / "weights" / "best.pt",
        "model_imgsz": 960,
        "slice_size": 1280,
        "overlap": 0.20,
    },
]

def yolo_to_coco_gt():
    images = []
    annotations = []
    ann_id = 1

    image_paths = sorted(
        p for p in VAL_IMG_DIR.iterdir()
        if p.suffix.lower() in [".jpg", ".jpeg", ".png"]
        and not p.name.startswith("._")
    )

    for img_id, img_path in enumerate(image_paths, start=1):
        with Image.open(img_path) as im:
            w, h = im.size

        images.append({
            "id": img_id,
            "file_name": img_path.name,
            "width": w,
            "height": h,
        })

        label_path = VAL_LBL_DIR / f"{img_path.stem}.txt"
        if not label_path.exists():
            continue

        seen = set()
        for line in label_path.read_text(errors="ignore").splitlines():
            parts = line.strip().split()
            if len(parts) != 5:
                continue

            cls, xc, yc, bw, bh = map(float, parts)
            cls = int(cls)

            # mirror Ultralytics duplicate cleanup
            key = tuple(round(x, 8) for x in [cls, xc, yc, bw, bh])
            if key in seen:
                continue
            seen.add(key)

            x = (xc - bw / 2) * w
            y = (yc - bh / 2) * h
            box_w = bw * w
            box_h = bh * h

            annotations.append({
                "id": ann_id,
                "image_id": img_id,
                "category_id": cls + 1,
                "bbox": [x, y, box_w, box_h],
                "area": box_w * box_h,
                "iscrowd": 0,
            })
            ann_id += 1

    return {
        "images": images,
        "annotations": annotations,
        "categories": CATEGORIES,
    }

GT_JSON = OUT_DIR / "val_gt_coco.json"
if not GT_JSON.exists():
    gt = yolo_to_coco_gt()
    GT_JSON.write_text(json.dumps(gt))
    print(f"Wrote GT: {GT_JSON} | images={len(gt['images'])}, anns={len(gt['annotations'])}")
else:
    print(f"Using existing GT: {GT_JSON}")

gt_data = json.loads(GT_JSON.read_text())
image_id_by_name = {img["file_name"]: img["id"] for img in gt_data["images"]}
image_paths = [VAL_IMG_DIR / img["file_name"] for img in gt_data["images"]]

def build_sahi_model(weights, model_imgsz, conf=0.001):
    # Try newer SAHI model type first, then fallback used by older SAHI builds.
    last_error = None
    for model_type in ["ultralytics", "yolov8"]:
        try:
            return AutoDetectionModel.from_pretrained(
                model_type=model_type,
                model_path=str(weights),
                confidence_threshold=conf,
                device="cuda:0",
                image_size=model_imgsz,
            )
        except Exception as e:
            last_error = e
    raise last_error

def run_sahi_predictions(run):
    run_out = OUT_DIR / run["name"]
    run_out.mkdir(parents=True, exist_ok=True)

    pred_json = run_out / "predictions.json"
    if pred_json.exists():
        print(f"Using existing predictions: {pred_json}")
        return pred_json

    assert run["weights"].exists(), f"Missing weights: {run['weights']}"

    model = build_sahi_model(run["weights"], run["model_imgsz"])
    preds = []

    for img_path in tqdm(image_paths, desc=run["name"]):
        result = get_sliced_prediction(
            image=str(img_path),
            detection_model=model,
            slice_height=run["slice_size"],
            slice_width=run["slice_size"],
            overlap_height_ratio=run["overlap"],
            overlap_width_ratio=run["overlap"],
            postprocess_type="NMS",
            postprocess_match_metric="IOU",
            postprocess_match_threshold=0.5,
            verbose=0,
        )

        image_id = image_id_by_name[img_path.name]

        for obj in result.object_prediction_list:
            cls_id = int(obj.category.id)
            score = float(obj.score.value)

            x1, y1, x2, y2 = obj.bbox.to_xyxy()
            x = float(x1)
            y = float(y1)
            w = float(x2 - x1)
            h = float(y2 - y1)

            if w <= 0 or h <= 0:
                continue

            preds.append({
                "image_id": image_id,
                "category_id": cls_id + 1,
                "bbox": [x, y, w, h],
                "score": score,
            })

    pred_json.write_text(json.dumps(preds))
    print(f"Wrote predictions: {pred_json} | preds={len(preds)}")
    return pred_json

def coco_eval_metrics(pred_json):
    coco_gt = COCO(str(GT_JSON))

    preds = json.loads(Path(pred_json).read_text())
    if len(preds) == 0:
        return {
            "aggregate_AP50": 0.0,
            "aggregate_AP50_95": 0.0,
            "vape_AP50": 0.0,
            "vape_AP50_95": 0.0,
            "lighter_AP50": 0.0,
            "lighter_AP50_95": 0.0,
        }

    coco_dt = coco_gt.loadRes(str(pred_json))

    def run_eval(cat_ids=None):
        ev = COCOeval(coco_gt, coco_dt, "bbox")
        if cat_ids is not None:
            ev.params.catIds = cat_ids
        ev.params.imgIds = sorted(image_id_by_name.values())

        # quiet pycocotools chatter
        with contextlib.redirect_stdout(io.StringIO()):
            ev.evaluate()
            ev.accumulate()
            ev.summarize()

        return {
            "AP50_95": float(ev.stats[0]),
            "AP50": float(ev.stats[1]),
        }

    agg = run_eval()
    vape = run_eval([1])
    lighter = run_eval([2])

    return {
        "aggregate_AP50": agg["AP50"],
        "aggregate_AP50_95": agg["AP50_95"],
        "vape_AP50": vape["AP50"],
        "vape_AP50_95": vape["AP50_95"],
        "lighter_AP50": lighter["AP50"],
        "lighter_AP50_95": lighter["AP50_95"],
    }

summary_rows = []

for run in TILE_RUNS:
    print("\n" + "=" * 80)
    print(run["name"])
    print("=" * 80)

    pred_json = run_sahi_predictions(run)
    metrics = coco_eval_metrics(pred_json)

    row = {
        "run": run["name"],
        "weights": str(run["weights"]),
        "model_imgsz": run["model_imgsz"],
        "slice_size": run["slice_size"],
        "overlap": run["overlap"],
        **metrics,
    }
    summary_rows.append(row)

    print(row)

summary_csv = OUT_DIR / "sahi_tiling_validation_summary.csv"
with summary_csv.open("w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
    writer.writeheader()
    writer.writerows(summary_rows)

print("\nSaved:", summary_csv)
print("\nSummary:")
for row in summary_rows:
    print(row)

Wrote GT: /workspace/uavape_v4_model_benchmark/tiling_eval/val_gt_coco.json | images=183, anns=302

================================================================================
v4_yolo26s_img640_sahi_tile1280_ov20
================================================================================

v4_yolo26s_img640_sahi_tile1280_ov20: 100%|██████████| 183/183 [02:03<00:00,  1.48it/s]

Wrote predictions: /workspace/uavape_v4_model_benchmark/tiling_eval/v4_yolo26s_img640_sahi_tile1280_ov20/predictions.json | preds=9131
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.03s)
creating index...
index created!
{'run': 'v4_yolo26s_img640_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/best.pt', 'model_imgsz': 640, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6398191379754871, 'aggregate_AP50_95': 0.484360499916287, 'vape_AP50': 0.7274123196699179, 'vape_AP50_95': 0.55774439313922, 'lighter_AP50': 0.5522259562810561, 'lighter_AP50_95': 0.410976606693354}

================================================================================
v4_yolo26s_img960_sahi_tile1280_ov20
================================================================================

v4_yolo26s_img960_sahi_tile1280_ov20:   8%|▊         | 14/183 [00:20<04:00,  1.42s/it]2026-06-10 15:27:07,042 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 427.2372741699219] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  32%|███▏      | 59/183 [00:32<00:22,  5.57it/s]2026-06-10 15:27:18,375 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1894.448974609375, 1536, 2043.6988525390625] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  43%|████▎     | 79/183 [00:35<00:21,  4.92it/s]2026-06-10 15:27:22,202 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 0, 1536, 163.5646514892578] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  57%|█████▋    | 104/183 [00:40<00:14,  5.33it/s]2026-06-10 15:27:27,162 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 0, 1536, 156.87229919433594] (ultralytics.py:285)
2026-06-10 15:27:27,163 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 0, 1536, 177.50228881835938] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  84%|████████▎ | 153/183 [01:28<00:36,  1.22s/it]2026-06-10 15:28:15,604 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 406.0858154296875] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  87%|████████▋ | 160/183 [01:37<00:30,  1.32s/it]2026-06-10 15:28:24,908 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 421.1159973144531] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20:  98%|█████████▊| 180/183 [02:02<00:03,  1.26s/it]2026-06-10 15:28:49,778 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 400.15118408203125] (ultralytics.py:285)
v4_yolo26s_img960_sahi_tile1280_ov20: 100%|██████████| 183/183 [02:06<00:00,  1.44it/s]

Wrote predictions: /workspace/uavape_v4_model_benchmark/tiling_eval/v4_yolo26s_img960_sahi_tile1280_ov20/predictions.json | preds=7568
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
{'run': 'v4_yolo26s_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6959228035897583, 'aggregate_AP50_95': 0.5102650897720695, 'vape_AP50': 0.8055384418215006, 'vape_AP50_95': 0.6055932807417023, 'lighter_AP50': 0.5863071653580161, 'lighter_AP50_95': 0.41493689880243684}

================================================================================
v4_yolo11s_img960_sahi_tile1280_ov20
================================================================================

v4_yolo11s_img960_sahi_tile1280_ov20:   5%|▍         | 9/183 [00:12<03:57,  1.37s/it]2026-06-10 15:29:06,822 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5364.68798828125, 4284, 5712] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:   6%|▌         | 11/183 [00:15<03:49,  1.34s/it]2026-06-10 15:29:09,424 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5385.607421875, 4284, 5710.77734375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  11%|█▏        | 21/183 [00:23<01:15,  2.14it/s]2026-06-10 15:29:17,319 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1086.67041015625, 1536, 1310.8988037109375] (ultralytics.py:285)
2026-06-10 15:29:17,320 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 942.1649169921875, 1536, 1170.073486328125] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  32%|███▏      | 59/183 [00:30<00:21,  5.65it/s]2026-06-10 15:29:23,927 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1892.464111328125, 1536, 2046.779296875] (ultralytics.py:285)
2026-06-10 15:29:23,927 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1953.6737060546875, 1536, 2047.76171875] (ultralytics.py:285)
2026-06-10 15:29:23,928 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1821.0570068359375, 1536, 2018.7994384765625] (ultralytics.py:285)
2026-06-10 15:29:23,928 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1745.38818359375, 1536, 1955.94921875] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  33%|███▎      | 60/183 [00:30<00:22,  5.54it/s]2026-06-10 15:29:24,113 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1952.060791015625, 1536, 2047.795166015625] (ultralytics.py:285)
2026-06-10 15:29:24,114 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1886.1444091796875, 1536, 2046.990966796875] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  34%|███▍      | 63/183 [00:31<00:20,  5.74it/s]2026-06-10 15:29:24,632 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1929.4581298828125, 1536, 2047.4378662109375] (ultralytics.py:285)
2026-06-10 15:29:24,633 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1777.3834228515625, 1536, 1986.8740234375] (ultralytics.py:285)
2026-06-10 15:29:24,633 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1961.8934326171875, 1536, 2047.59765625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  35%|███▍      | 64/183 [00:31<00:21,  5.66it/s]2026-06-10 15:29:24,817 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1957.5191650390625, 1536, 2047.4378662109375] (ultralytics.py:285)
2026-06-10 15:29:24,818 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 1901.0794677734375, 1536, 2046.682861328125] (ultralytics.py:285)
2026-06-10 15:29:24,818 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 408.185302734375, 1536, 617.665771484375] (ultralytics.py:285)
2026-06-10 15:29:24,818 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 339.62481689453125, 1536, 554.8389892578125] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  37%|███▋      | 67/183 [00:31<00:20,  5.60it/s]2026-06-10 15:29:25,357 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 73.29531860351562, 1536, 347.0196228027344] (ultralytics.py:285)
2026-06-10 15:29:25,358 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 3.677799701690674, 1536, 301.20013427734375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  43%|████▎     | 79/183 [00:34<00:19,  5.26it/s]2026-06-10 15:29:27,527 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 803.9210205078125, 1536, 1045.6480712890625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  46%|████▌     | 84/183 [00:35<00:19,  4.95it/s]2026-06-10 15:29:28,545 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 838.56591796875, 1536, 1137.3870849609375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  57%|█████▋    | 104/183 [00:38<00:14,  5.51it/s]2026-06-10 15:29:32,238 - sahi - WARNING - ignoring invalid prediction with bbox: [1536, 0, 1536, 107.96794891357422] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  64%|██████▍   | 117/183 [00:42<00:35,  1.87it/s]2026-06-10 15:29:36,598 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5478.97119140625, 4284, 5709.78076171875] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  64%|██████▍   | 118/183 [00:43<00:50,  1.29it/s]2026-06-10 15:29:37,904 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 259.422119140625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  80%|████████  | 147/183 [01:17<00:40,  1.13s/it]2026-06-10 15:30:11,517 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5402.6708984375, 4284, 5711.5322265625] (ultralytics.py:285)
2026-06-10 15:30:11,518 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 249.81129455566406, 4284, 915.5128173828125] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  83%|████████▎ | 151/183 [01:22<00:37,  1.16s/it]2026-06-10 15:30:16,187 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5379.5869140625, 4284, 5711.3369140625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  84%|████████▎ | 153/183 [01:24<00:36,  1.22s/it]2026-06-10 15:30:18,805 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 297.1825256347656] (ultralytics.py:285)
2026-06-10 15:30:18,806 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2998.07568359375, 4284, 3560.71240234375] (ultralytics.py:285)
2026-06-10 15:30:18,806 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3141.34716796875, 4284, 3700.941162109375] (ultralytics.py:285)
2026-06-10 15:30:18,807 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 431.4117126464844] (ultralytics.py:285)
2026-06-10 15:30:18,807 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5387.51513671875, 4284, 5712] (ultralytics.py:285)
2026-06-10 15:30:18,807 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 188.92678833007812] (ultralytics.py:285)
2026-06-10 15:30:18,807 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2870.849365234375, 4284, 3409.53955078125] (ultralytics.py:285)
2026-06-10 15:30:18,807 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5259.7939453125, 4284, 5709.65966796875] (ultralytics.py:285)
2026-06-10 15:30:18,808 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4245.33447265625, 4284, 4812.728515625] (ultralytics.py:285)
2026-06-10 15:30:18,808 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3340.043212890625, 4284, 3854.91357421875] (ultralytics.py:285)
2026-06-10 15:30:18,808 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2781.636962890625, 4284, 3312.871826171875] (ultralytics.py:285)
2026-06-10 15:30:18,808 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2619.60107421875, 4284, 3154.6875] (ultralytics.py:285)
2026-06-10 15:30:18,809 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2543.659423828125, 4284, 3042.088134765625] (ultralytics.py:285)
2026-06-10 15:30:18,809 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3532.681640625, 4284, 4058.790283203125] (ultralytics.py:285)
2026-06-10 15:30:18,809 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2164.520263671875, 4284, 2682.730224609375] (ultralytics.py:285)
2026-06-10 15:30:18,809 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3453.825927734375, 4284, 3964.822998046875] (ultralytics.py:285)
2026-06-10 15:30:18,809 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 71.70909118652344, 4284, 559.9810180664062] (ultralytics.py:285)
2026-06-10 15:30:18,810 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1991.0904541015625, 4284, 2458.730712890625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  84%|████████▍ | 154/183 [01:25<00:36,  1.26s/it]2026-06-10 15:30:20,129 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5386.2177734375, 4284, 5712] (ultralytics.py:285)
2026-06-10 15:30:20,130 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3107.48681640625, 4284, 3625.399169921875] (ultralytics.py:285)
2026-06-10 15:30:20,130 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3302.341796875, 4284, 3821.8642578125] (ultralytics.py:285)
2026-06-10 15:30:20,130 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3191.7666015625, 4284, 3722.6640625] (ultralytics.py:285)
2026-06-10 15:30:20,130 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3588.79736328125, 4284, 4113.984375] (ultralytics.py:285)
2026-06-10 15:30:20,131 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4300.904296875, 4284, 4807.6259765625] (ultralytics.py:285)
2026-06-10 15:30:20,131 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2791.629150390625, 4284, 3262.486572265625] (ultralytics.py:285)
2026-06-10 15:30:20,131 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2970.8837890625, 4284, 3503.03466796875] (ultralytics.py:285)
2026-06-10 15:30:20,132 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1693.5179443359375, 4284, 2191.500732421875] (ultralytics.py:285)
2026-06-10 15:30:20,132 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5157.2890625, 4284, 5712] (ultralytics.py:285)
2026-06-10 15:30:20,132 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3490.182861328125, 4284, 4023.66748046875] (ultralytics.py:285)
2026-06-10 15:30:20,132 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 326.0892333984375] (ultralytics.py:285)
2026-06-10 15:30:20,132 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2877.0556640625, 4284, 3362.03466796875] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  85%|████████▌ | 156/183 [01:28<00:34,  1.28s/it]2026-06-10 15:30:22,704 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4519.7470703125, 4284, 5183.62109375] (ultralytics.py:285)
2026-06-10 15:30:22,705 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5324.1123046875, 4284, 5712] (ultralytics.py:285)
2026-06-10 15:30:22,705 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1686.7196044921875, 4284, 2166.052001953125] (ultralytics.py:285)
2026-06-10 15:30:22,706 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4415.4541015625, 4284, 5023.2021484375] (ultralytics.py:285)
2026-06-10 15:30:22,706 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2647.38671875, 4284, 3120.55419921875] (ultralytics.py:285)
2026-06-10 15:30:22,706 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1767.986083984375, 4284, 2321.032958984375] (ultralytics.py:285)
2026-06-10 15:30:22,706 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3386.14990234375, 4284, 3943.734130859375] (ultralytics.py:285)
2026-06-10 15:30:22,706 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2551.16748046875, 4284, 3050.048095703125] (ultralytics.py:285)
2026-06-10 15:30:22,707 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3207.49951171875, 4284, 3752.18603515625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  86%|████████▌ | 157/183 [01:29<00:33,  1.27s/it]2026-06-10 15:30:24,126 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5272.490234375, 4284, 5708.90185546875] (ultralytics.py:285)
2026-06-10 15:30:24,127 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4349.92626953125, 4284, 4873.96923828125] (ultralytics.py:285)
2026-06-10 15:30:24,127 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5181.927734375, 4284, 5712] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  86%|████████▋ | 158/183 [01:31<00:33,  1.34s/it]2026-06-10 15:30:25,504 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 330.0880432128906] (ultralytics.py:285)
2026-06-10 15:30:25,505 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 412.954833984375] (ultralytics.py:285)
2026-06-10 15:30:25,505 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 172.42147827148438] (ultralytics.py:285)
2026-06-10 15:30:25,505 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3051.078857421875, 4284, 3592.778564453125] (ultralytics.py:285)
2026-06-10 15:30:25,506 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2705.32470703125, 4284, 3206.461181640625] (ultralytics.py:285)
2026-06-10 15:30:25,506 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2469.886474609375, 4284, 2905.181396484375] (ultralytics.py:285)
2026-06-10 15:30:25,506 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3436.49169921875, 4284, 4016.352294921875] (ultralytics.py:285)
2026-06-10 15:30:25,506 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3711.833984375, 4284, 4272.36865234375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  87%|████████▋ | 159/183 [01:32<00:31,  1.33s/it]2026-06-10 15:30:26,757 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4845.6279296875, 4284, 5450.52734375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  88%|████████▊ | 161/183 [01:35<00:28,  1.31s/it]2026-06-10 15:30:29,351 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2476.207763671875, 4284, 3035.058837890625] (ultralytics.py:285)
2026-06-10 15:30:29,352 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1515.4307861328125, 4284, 2101.906005859375] (ultralytics.py:285)
2026-06-10 15:30:29,353 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5377.634765625, 4284, 5712] (ultralytics.py:285)
2026-06-10 15:30:29,356 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2044.9031982421875, 4284, 2612.58203125] (ultralytics.py:285)
2026-06-10 15:30:29,356 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2235.64013671875, 4284, 2806.960693359375] (ultralytics.py:285)
2026-06-10 15:30:29,357 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1385.556396484375, 4284, 1965.059326171875] (ultralytics.py:285)
2026-06-10 15:30:29,357 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 4887.1845703125, 4284, 5468.36865234375] (ultralytics.py:285)
2026-06-10 15:30:29,357 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5059.73779296875, 4284, 5616.76171875] (ultralytics.py:285)
2026-06-10 15:30:29,358 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1666.7796630859375, 4284, 2199.176025390625] (ultralytics.py:285)
2026-06-10 15:30:29,358 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 859.567626953125, 4284, 1424.8233642578125] (ultralytics.py:285)
2026-06-10 15:30:29,358 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2611.20166015625, 4284, 3194.782470703125] (ultralytics.py:285)
2026-06-10 15:30:29,359 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 2837.80419921875, 4284, 3429.5458984375] (ultralytics.py:285)
2026-06-10 15:30:29,359 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1773.451171875, 4284, 2311.70068359375] (ultralytics.py:285)
2026-06-10 15:30:29,359 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1964.90966796875, 4284, 2484.94384765625] (ultralytics.py:285)
2026-06-10 15:30:29,360 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3983.735595703125, 4284, 4489.017578125] (ultralytics.py:285)
2026-06-10 15:30:29,360 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 1304.576171875, 4284, 1839.8829345703125] (ultralytics.py:285)
2026-06-10 15:30:29,360 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3102.253662109375, 4284, 3640.335205078125] (ultralytics.py:285)
2026-06-10 15:30:29,361 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3728.968505859375, 4284, 4265.75830078125] (ultralytics.py:285)
2026-06-10 15:30:29,362 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 774.6642456054688, 4284, 1322.68994140625] (ultralytics.py:285)
2026-06-10 15:30:29,362 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 999.459716796875, 4284, 1518.3267822265625] (ultralytics.py:285)
2026-06-10 15:30:29,363 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 3208.051513671875, 4284, 3720.64990234375] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  90%|████████▉ | 164/183 [01:39<00:25,  1.33s/it]2026-06-10 15:30:33,384 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5381.2666015625, 4284, 5711.32958984375] (ultralytics.py:285)
2026-06-10 15:30:33,385 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5254.72802734375, 4284, 5708.71337890625] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  97%|█████████▋| 178/183 [01:56<00:06,  1.28s/it]2026-06-10 15:30:50,440 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 5430.07080078125, 4284, 5710.8642578125] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20:  98%|█████████▊| 180/183 [01:58<00:03,  1.23s/it]2026-06-10 15:30:52,801 - sahi - WARNING - ignoring invalid prediction with bbox: [4284, 0, 4284, 443.3193054199219] (ultralytics.py:285)
v4_yolo11s_img960_sahi_tile1280_ov20: 100%|██████████| 183/183 [02:02<00:00,  1.50it/s]

Wrote predictions: /workspace/uavape_v4_model_benchmark/tiling_eval/v4_yolo11s_img960_sahi_tile1280_ov20/predictions.json | preds=10449
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.28s)
creating index...
index created!
{'run': 'v4_yolo11s_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.680782721685517, 'aggregate_AP50_95': 0.5112363991427478, 'vape_AP50': 0.7659535711757335, 'vape_AP50_95': 0.5847864098080153, 'lighter_AP50': 0.5956118721953008, 'lighter_AP50_95': 0.43768638847748004}

================================================================================
v4_yolo11n_img960_sahi_tile1280_ov20
================================================================================

v4_yolo11n_img960_sahi_tile1280_ov20: 100%|██████████| 183/183 [02:02<00:00,  1.50it/s]

Wrote predictions: /workspace/uavape_v4_model_benchmark/tiling_eval/v4_yolo11n_img960_sahi_tile1280_ov20/predictions.json | preds=14250
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.26s)
creating index...
index created!
{'run': 'v4_yolo11n_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo11n_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6780384370508052, 'aggregate_AP50_95': 0.5077306319346564, 'vape_AP50': 0.7587143200522484, 'vape_AP50_95': 0.5693738484529441, 'lighter_AP50': 0.5973625540493619, 'lighter_AP50_95': 0.4460874154163686}

Saved: /workspace/uavape_v4_model_benchmark/tiling_eval/sahi_tiling_validation_summary.csv

Summary:
{'run': 'v4_yolo26s_img640_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img640/weights/best.pt', 'model_imgsz': 640, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6398191379754871, 'aggregate_AP50_95': 0.484360499916287, 'vape_AP50': 0.7274123196699179, 'vape_AP50_95': 0.55774439313922, 'lighter_AP50': 0.5522259562810561, 'lighter_AP50_95': 0.410976606693354}
{'run': 'v4_yolo26s_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo26s_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6959228035897583, 'aggregate_AP50_95': 0.5102650897720695, 'vape_AP50': 0.8055384418215006, 'vape_AP50_95': 0.6055932807417023, 'lighter_AP50': 0.5863071653580161, 'lighter_AP50_95': 0.41493689880243684}
{'run': 'v4_yolo11s_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo11s_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.680782721685517, 'aggregate_AP50_95': 0.5112363991427478, 'vape_AP50': 0.7659535711757335, 'vape_AP50_95': 0.5847864098080153, 'lighter_AP50': 0.5956118721953008, 'lighter_AP50_95': 0.43768638847748004}
{'run': 'v4_yolo11n_img960_sahi_tile1280_ov20', 'weights': '/workspace/uavape_v4_model_benchmark/runs/v4_yolo11n_img960/weights/best.pt', 'model_imgsz': 960, 'slice_size': 1280, 'overlap': 0.2, 'aggregate_AP50': 0.6780384370508052, 'aggregate_AP50_95': 0.5077306319346564, 'vape_AP50': 0.7587143200522484, 'vape_AP50_95': 0.5693738484529441, 'lighter_AP50': 0.5973625540493619, 'lighter_AP50_95': 0.4460874154163686}

In [45]:
!pip install -q -U gdown

In [47]:
from pathlib import Path
import zipfile, shutil, re
import gdown

ROOT = Path("/workspace/uavape_v4_model_benchmark")
ADDONS = ROOT / "addons"
ADDONS.mkdir(parents=True, exist_ok=True)

DRIVE_FILES = {
    "scraped": "https://drive.google.com/file/d/1oApe7tstJrBlT1dulzC5wMw_ej-se6qg/view?usp=sharing",
    "synthetic": "https://drive.google.com/file/d/1kl0MgZg7iMzZKK81zo93pcTZYzFrj3kG/view?usp=sharing",
}

def drive_id_from_ref(ref):
    ref = str(ref).strip()
    if "drive.google.com" not in ref:
        return ref
    m = re.search(r"/file/d/([^/]+)", ref)
    if m:
        return m.group(1)
    m = re.search(r"[?&]id=([^&]+)", ref)
    if m:
        return m.group(1)
    raise ValueError(f"Could not extract Drive file ID from: {ref}")

def download_drive_file(name, file_ref):
    out_zip = ADDONS / f"{name}.zip"
    file_id = drive_id_from_ref(file_ref)
    url = f"https://drive.google.com/uc?id={file_id}"

    print(f"Downloading {name} from file id {file_id}")
    gdown.download(url, str(out_zip), quiet=False)

    if not out_zip.exists() or out_zip.stat().st_size == 0:
        raise FileNotFoundError(f"Download failed or empty: {out_zip}")
    print(name, "zip size MB:", round(out_zip.stat().st_size / 1e6, 2))
    return out_zip

def extract_source_zip(source_name, zip_path):
    out_dir = ADDONS / source_name
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(out_dir)

    image_dirs = list(out_dir.rglob("images"))
    label_dirs = list(out_dir.rglob("labels"))

    if image_dirs and label_dirs and image_dirs[0].parent != out_dir:
        nested = image_dirs[0].parent
        flat_tmp = ADDONS / f"_{source_name}_flat_tmp"
        if flat_tmp.exists():
            shutil.rmtree(flat_tmp)
        flat_tmp.mkdir(parents=True)
        shutil.copytree(nested / "images", flat_tmp / "images")
        shutil.copytree(nested / "labels", flat_tmp / "labels")
        shutil.rmtree(out_dir)
        flat_tmp.rename(out_dir)

    print(source_name, "ready:", out_dir)
    print("images:", len(list((out_dir / "images").glob("*"))))
    print("labels:", len(list((out_dir / "labels").glob("*.txt"))))

for name, file_ref in DRIVE_FILES.items():
    zip_path = download_drive_file(name, file_ref)
    extract_source_zip(name, zip_path)

Downloading scraped from file id 1oApe7tstJrBlT1dulzC5wMw_ej-se6qg

Downloading...
From (original): https://drive.google.com/uc?id=1oApe7tstJrBlT1dulzC5wMw_ej-se6qg
From (redirected): https://drive.google.com/uc?id=1oApe7tstJrBlT1dulzC5wMw_ej-se6qg&confirm=t&uuid=2fe72a6e-9a89-4519-a68d-77757a90bf90
To: /workspace/uavape_v4_model_benchmark/addons/scraped.zip
100%|██████████| 271M/271M [00:04<00:00, 63.7MB/s]

scraped zip size MB: 270.53
scraped ready: /workspace/uavape_v4_model_benchmark/addons/scraped
images: 2906
labels: 2906
Downloading synthetic from file id 1kl0MgZg7iMzZKK81zo93pcTZYzFrj3kG

Downloading...
From (original): https://drive.google.com/uc?id=1kl0MgZg7iMzZKK81zo93pcTZYzFrj3kG
From (redirected): https://drive.google.com/uc?id=1kl0MgZg7iMzZKK81zo93pcTZYzFrj3kG&confirm=t&uuid=140a61f6-ce50-4514-a062-c57cae283561
To: /workspace/uavape_v4_model_benchmark/addons/synthetic.zip
100%|██████████| 1.31G/1.31G [00:16<00:00, 81.1MB/s]

synthetic zip size MB: 1310.05
synthetic ready: /workspace/uavape_v4_model_benchmark/addons/synthetic
images: 355
labels: 355

In [48]:
from pathlib import Path
import random
import shutil
import csv
import yaml
from collections import Counter

ROOT = Path("/workspace/uavape_v4_model_benchmark")
BASE = ROOT / "datasets" / "v4_real_final_20260610"
OUT_ROOT = ROOT / "datasets" / "v4_data_ablation_20260610"

SEED = 42
DOSES = [88, 177, 355]
IMG_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

SCRAPED_CANDIDATES = [
    ROOT / "addons" / "scraped",
    ROOT / "old_sources" / "external_vape_aggregated_vape_only" / "yolo_pool" / "external_positive",
    ROOT / "experiments" / "ml" / "results" / "external_vape_aggregated_vape_only" / "yolo_pool" / "external_positive",
]

SYNTHETIC_CANDIDATES = [
    ROOT / "addons" / "synthetic",
    ROOT / "old_sources" / "synthetic_promoted_only" / "splits" / "default_70_20_10_e3" / "train",
    ROOT / "experiments" / "ml" / "results" / "synthetic_promoted_only" / "splits" / "default_70_20_10_e3" / "train",
]

def normalise_pool_dir(pool_dir):
    pool_dir = Path(pool_dir)
    if (pool_dir / "images").exists() and (pool_dir / "labels").exists():
        return pool_dir / "images", pool_dir / "labels"
    if (pool_dir / "train" / "images").exists() and (pool_dir / "train" / "labels").exists():
        return pool_dir / "train" / "images", pool_dir / "train" / "labels"
    return None, None

def list_yolo_pairs(pool_dir):
    images_dir, labels_dir = normalise_pool_dir(pool_dir)
    if images_dir is None:
        return []
    pairs = []
    for img in sorted(images_dir.iterdir()):
        if img.suffix.lower() not in IMG_EXTS:
            continue
        lab = labels_dir / f"{img.stem}.txt"
        if lab.exists():
            pairs.append((img, lab))
    return pairs

def find_first_pool(candidates, label):
    checked = []
    for candidate in candidates:
        pairs = list_yolo_pairs(candidate)
        checked.append((candidate, len(pairs)))
        if pairs:
            print(f"{label} pool selected: {candidate} | labelled images={len(pairs)}")
            return Path(candidate)
    print(f"No {label} pool found. Checked:")
    for path, count in checked:
        print(f"  {path} | labelled images={count}")
    return None

def audit_pool(pool_dir, label):
    pairs = list_yolo_pairs(pool_dir)
    cls_counts = Counter()
    malformed = []
    empty = 0
    for _, lab in pairs:
        text = lab.read_text().splitlines()
        if not text:
            empty += 1
            continue
        for line in text:
            parts = line.split()
            if len(parts) != 5:
                malformed.append(str(lab))
                continue
            cls_counts[parts[0]] += 1
    print(f"\n{label} audit")
    print("pool:", pool_dir)
    print("labelled images:", len(pairs))
    print("class ids:", dict(sorted(cls_counts.items())))
    print("empty labels:", empty)
    print("malformed labels:", len(set(malformed)))
    if set(cls_counts.keys()) - {"0"}:
        raise ValueError(f"{label} contains class IDs other than 0. Do not use until remapped/audited.")
    if len(pairs) < max(DOSES):
        raise ValueError(f"{label} has only {len(pairs)} labelled images; need at least {max(DOSES)}.")
    return pairs

SCRAPED = find_first_pool(SCRAPED_CANDIDATES, "scraped")
SYNTHETIC = find_first_pool(SYNTHETIC_CANDIDATES, "synthetic")

if SCRAPED is None:
    raise FileNotFoundError("Scraped pool not found. Copy it into /workspace/uavape_v4_model_benchmark/addons/scraped or edit SCRAPED_CANDIDATES.")
if SYNTHETIC is None:
    raise FileNotFoundError("Synthetic pool not found. Copy it into /workspace/uavape_v4_model_benchmark/addons/synthetic or edit SYNTHETIC_CANDIDATES.")

scraped_pairs = audit_pool(SCRAPED, "scraped")
synthetic_pairs = audit_pool(SYNTHETIC, "synthetic")

print("\nOK: add-on pools are one-class class-0 sources, compatible with V4 class 0 = vape.")

scraped pool selected: /workspace/uavape_v4_model_benchmark/addons/scraped | labelled images=2906
synthetic pool selected: /workspace/uavape_v4_model_benchmark/addons/synthetic | labelled images=355

scraped audit
pool: /workspace/uavape_v4_model_benchmark/addons/scraped
labelled images: 2906
class ids: {'0': 4438}
empty labels: 0
malformed labels: 0

synthetic audit
pool: /workspace/uavape_v4_model_benchmark/addons/synthetic
labelled images: 355
class ids: {'0': 355}
empty labels: 0
malformed labels: 0

OK: add-on pools are one-class class-0 sources, compatible with V4 class 0 = vape.

In [49]:
from pathlib import Path
import random
import shutil
import csv
import yaml
from collections import Counter

def sample_nested_pairs(pool_dir, doses, seed=SEED):
    pairs = list_yolo_pairs(pool_dir)
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    max_n = max(doses)
    selected = shuffled[:max_n]
    return {n: sorted(selected[:n], key=lambda p: p[0].name) for n in doses}

def copy_split(src_dataset, dst_dataset, split):
    for kind in ["images", "labels"]:
        src = src_dataset / kind / split
        dst = dst_dataset / kind / split
        dst.mkdir(parents=True, exist_ok=True)
        for item in sorted(src.iterdir()):
            if item.is_file():
                shutil.copy2(item, dst / item.name)

def copy_addons(dst_dataset, pairs, prefix):
    img_dst = dst_dataset / "images" / "train"
    lab_dst = dst_dataset / "labels" / "train"
    rows = []
    for img, lab in pairs:
        img_name = f"{prefix}_{img.name}"
        lab_name = f"{prefix}_{lab.name}"
        shutil.copy2(img, img_dst / img_name)
        shutil.copy2(lab, lab_dst / lab_name)
        rows.append({"source": prefix, "image": str(img), "label": str(lab), "copied_image": img_name})
    return rows

def count_split(dataset, split):
    image_dir = dataset / "images" / split
    label_dir = dataset / "labels" / split
    image_count = len([p for p in image_dir.iterdir() if p.suffix.lower() in IMG_EXTS])
    label_count = len([p for p in label_dir.iterdir() if p.suffix.lower() == ".txt"])
    class_counts = Counter()
    box_count = 0
    for lab in label_dir.glob("*.txt"):
        for line in lab.read_text().splitlines():
            if not line.strip():
                continue
            cls = int(float(line.split()[0]))
            class_counts[cls] += 1
            box_count += 1
    return image_count, label_count, box_count, class_counts

def write_dataset_yaml(dataset):
    data = {
        "path": str(dataset),
        "train": "images/train",
        "val": "images/val",
        "test": "images/test",
        "names": {0: "vape", 1: "lighter"},
    }
    with open(dataset / "dataset.yaml", "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)

def build_dataset(name, scraped=None, synthetic=None):
    scraped = scraped or []
    synthetic = synthetic or []
    dst = OUT_ROOT / name
    if dst.exists():
        shutil.rmtree(dst)
    for split in ["train", "val", "test"]:
        copy_split(BASE, dst, split)

    manifest_rows = []
    manifest_rows += copy_addons(dst, scraped, "scraped")
    manifest_rows += copy_addons(dst, synthetic, "synthetic")
    write_dataset_yaml(dst)

    with open(dst / "addon_manifest.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["source", "image", "label", "copied_image"])
        writer.writeheader()
        writer.writerows(manifest_rows)

    summary_rows = []
    for split in ["train", "val", "test"]:
        images, labels, boxes, class_counts = count_split(dst, split)
        summary_rows.append({
            "dataset": name,
            "split": split,
            "images": images,
            "labels": labels,
            "boxes": boxes,
            "vape_boxes": class_counts.get(0, 0),
            "lighter_boxes": class_counts.get(1, 0),
        })

    with open(dst / "dataset_summary.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=summary_rows[0].keys())
        writer.writeheader()
        writer.writerows(summary_rows)

    print(f"\n{name}")
    for row in summary_rows:
        print(row)
    return dst

OUT_ROOT.mkdir(parents=True, exist_ok=True)

scraped_samples = sample_nested_pairs(SCRAPED, DOSES, seed=SEED)
synthetic_samples = sample_nested_pairs(SYNTHETIC, DOSES, seed=SEED)

ABLATION_DATASETS = []
ABLATION_DATASETS.append(build_dataset("v4_ablate_A0_real_only"))

for dose in DOSES:
    ABLATION_DATASETS.append(
        build_dataset(f"v4_ablate_S{dose}_scraped", scraped=scraped_samples[dose])
    )

for dose in DOSES:
    ABLATION_DATASETS.append(
        build_dataset(f"v4_ablate_Y{dose}_synthetic", synthetic=synthetic_samples[dose])
    )

ABLATION_DATASETS.append(
    build_dataset(
        "v4_ablate_S355_Y355_combined",
        scraped=scraped_samples[355],
        synthetic=synthetic_samples[355],
    )
)

ABLATIONS = [p.name for p in ABLATION_DATASETS]
print("\nAblations ready:")
for name in ABLATIONS:
    print(" ", name, OUT_ROOT / name / "dataset.yaml")

v4_ablate_A0_real_only
{'dataset': 'v4_ablate_A0_real_only', 'split': 'train', 'images': 837, 'labels': 837, 'boxes': 1317, 'vape_boxes': 870, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_A0_real_only', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_A0_real_only', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S88_scraped
{'dataset': 'v4_ablate_S88_scraped', 'split': 'train', 'images': 925, 'labels': 925, 'boxes': 1440, 'vape_boxes': 993, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S88_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S88_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S177_scraped
{'dataset': 'v4_ablate_S177_scraped', 'split': 'train', 'images': 1014, 'labels': 1014, 'boxes': 1579, 'vape_boxes': 1132, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S177_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S177_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S355_scraped
{'dataset': 'v4_ablate_S355_scraped', 'split': 'train', 'images': 1192, 'labels': 1192, 'boxes': 1864, 'vape_boxes': 1417, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S355_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S355_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

OSError: [Errno 122] Disk quota exceeded

In [50]:
from pathlib import Path
import shutil

ROOT = Path("/workspace/uavape_v4_model_benchmark")
OUT_ROOT = ROOT / "datasets" / "v4_data_ablation_20260610"
ADDONS = ROOT / "addons"

if OUT_ROOT.exists():
    shutil.rmtree(OUT_ROOT)
    print("Removed partial ablation datasets:", OUT_ROOT)

for z in [ADDONS / "scraped.zip", ADDONS / "synthetic.zip"]:
    if z.exists():
        z.unlink()
        print("Removed zip:", z)

Removed partial ablation datasets: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610
Removed zip: /workspace/uavape_v4_model_benchmark/addons/scraped.zip
Removed zip: /workspace/uavape_v4_model_benchmark/addons/synthetic.zip

In [51]:
from pathlib import Path
import random, shutil, csv, yaml, os
from collections import Counter

def link_file(src, dst):
    src = Path(src).resolve()
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        os.link(src, dst)  # no extra disk if same filesystem
    except OSError:
        os.symlink(src, dst)  # fallback, also no image copy

def sample_nested_pairs(pool_dir, doses, seed=SEED):
    pairs = list_yolo_pairs(pool_dir)
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    selected = shuffled[:max(doses)]
    return {n: sorted(selected[:n], key=lambda p: p[0].name) for n in doses}

def copy_split(src_dataset, dst_dataset, split):
    for kind in ["images", "labels"]:
        src = src_dataset / kind / split
        dst = dst_dataset / kind / split
        dst.mkdir(parents=True, exist_ok=True)
        for item in sorted(src.iterdir()):
            if item.is_file():
                link_file(item, dst / item.name)

def copy_addons(dst_dataset, pairs, prefix):
    rows = []
    for img, lab in pairs:
        img_name = f"{prefix}_{img.name}"
        lab_name = f"{prefix}_{lab.name}"
        link_file(img, dst_dataset / "images" / "train" / img_name)
        link_file(lab, dst_dataset / "labels" / "train" / lab_name)
        rows.append({"source": prefix, "image": str(img), "label": str(lab), "copied_image": img_name})
    return rows

def count_split(dataset, split):
    image_dir = dataset / "images" / split
    label_dir = dataset / "labels" / split
    image_count = len([p for p in image_dir.iterdir() if p.suffix.lower() in IMG_EXTS])
    label_count = len([p for p in label_dir.iterdir() if p.suffix.lower() == ".txt"])
    class_counts = Counter()
    box_count = 0
    for lab in label_dir.glob("*.txt"):
        for line in lab.read_text().splitlines():
            if not line.strip():
                continue
            cls = int(float(line.split()[0]))
            class_counts[cls] += 1
            box_count += 1
    return image_count, label_count, box_count, class_counts

def write_dataset_yaml(dataset):
    data = {
        "path": str(dataset),
        "train": "images/train",
        "val": "images/val",
        "test": "images/test",
        "names": {0: "vape", 1: "lighter"},
    }
    with open(dataset / "dataset.yaml", "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)

def build_dataset(name, scraped=None, synthetic=None):
    scraped = scraped or []
    synthetic = synthetic or []
    dst = OUT_ROOT / name
    if dst.exists():
        shutil.rmtree(dst)

    for split in ["train", "val", "test"]:
        copy_split(BASE, dst, split)

    manifest_rows = []
    manifest_rows += copy_addons(dst, scraped, "scraped")
    manifest_rows += copy_addons(dst, synthetic, "synthetic")
    write_dataset_yaml(dst)

    with open(dst / "addon_manifest.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["source", "image", "label", "copied_image"])
        writer.writeheader()
        writer.writerows(manifest_rows)

    summary_rows = []
    for split in ["train", "val", "test"]:
        images, labels, boxes, class_counts = count_split(dst, split)
        row = {
            "dataset": name,
            "split": split,
            "images": images,
            "labels": labels,
            "boxes": boxes,
            "vape_boxes": class_counts.get(0, 0),
            "lighter_boxes": class_counts.get(1, 0),
        }
        summary_rows.append(row)

    with open(dst / "dataset_summary.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=summary_rows[0].keys())
        writer.writeheader()
        writer.writerows(summary_rows)

    print(f"\n{name}")
    for row in summary_rows:
        print(row)
    return dst

OUT_ROOT.mkdir(parents=True, exist_ok=True)

scraped_samples = sample_nested_pairs(SCRAPED, DOSES, seed=SEED)
synthetic_samples = sample_nested_pairs(SYNTHETIC, DOSES, seed=SEED)

ABLATION_DATASETS = [build_dataset("v4_ablate_A0_real_only")]

for dose in DOSES:
    ABLATION_DATASETS.append(build_dataset(f"v4_ablate_S{dose}_scraped", scraped=scraped_samples[dose]))

for dose in DOSES:
    ABLATION_DATASETS.append(build_dataset(f"v4_ablate_Y{dose}_synthetic", synthetic=synthetic_samples[dose]))

ABLATION_DATASETS.append(
    build_dataset("v4_ablate_S355_Y355_combined", scraped=scraped_samples[355], synthetic=synthetic_samples[355])
)

ABLATIONS = [p.name for p in ABLATION_DATASETS]
print("\nAblations ready:")
for name in ABLATIONS:
    print(" ", name, OUT_ROOT / name / "dataset.yaml")

v4_ablate_A0_real_only
{'dataset': 'v4_ablate_A0_real_only', 'split': 'train', 'images': 837, 'labels': 837, 'boxes': 1317, 'vape_boxes': 870, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_A0_real_only', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_A0_real_only', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S88_scraped
{'dataset': 'v4_ablate_S88_scraped', 'split': 'train', 'images': 925, 'labels': 925, 'boxes': 1440, 'vape_boxes': 993, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S88_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S88_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S177_scraped
{'dataset': 'v4_ablate_S177_scraped', 'split': 'train', 'images': 1014, 'labels': 1014, 'boxes': 1579, 'vape_boxes': 1132, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S177_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S177_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

v4_ablate_S355_scraped
{'dataset': 'v4_ablate_S355_scraped', 'split': 'train', 'images': 1192, 'labels': 1192, 'boxes': 1864, 'vape_boxes': 1417, 'lighter_boxes': 447}
{'dataset': 'v4_ablate_S355_scraped', 'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'dataset': 'v4_ablate_S355_scraped', 'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}

OSError: [Errno 122] Disk quota exceeded

In [52]:
from pathlib import Path
import shutil

ROOT = Path("/workspace/uavape_v4_model_benchmark")
OUT_ROOT = ROOT / "datasets" / "v4_data_ablation_20260610"

if OUT_ROOT.exists():
    shutil.rmtree(OUT_ROOT)
    print("Removed:", OUT_ROOT)

# Optional disk check
!df -h /workspace
!du -sh /workspace/uavape_v4_model_benchmark/* 2>/dev/null | sort -h

Removed: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610
Filesystem                   Size  Used Avail Use% Mounted on
mfs#us-ga-2.runpod.net:9421  825T  548T  277T  67% /workspace
2.5K	/workspace/uavape_v4_model_benchmark/v4_per_class_val_summary.csv
16M	/workspace/uavape_v4_model_benchmark/tiling_eval
906M	/workspace/uavape_v4_model_benchmark/runs
1.5G	/workspace/uavape_v4_model_benchmark/addons
7.7G	/workspace/uavape_v4_model_benchmark/datasets

In [53]:
from pathlib import Path
import random, shutil, csv, yaml, os
from collections import Counter
from ultralytics import YOLO

DATA_ROOT = ROOT / "datasets" / "v4_data_ablation_20260610"
CURRENT = DATA_ROOT / "_current_dataset"
RUNS_ROOT = ROOT / "runs_data_ablation"

MODEL = "yolo26s.pt"
IMGSZ = 1280
EPOCHS = 100
SEED = 42

def link_file(src, dst):
    src = Path(src).resolve()
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        os.symlink(src, dst)  # lowest quota pressure
    except OSError:
        os.link(src, dst)

def sample_nested_pairs(pool_dir, doses, seed=SEED):
    pairs = list_yolo_pairs(pool_dir)
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    selected = shuffled[:max(doses)]
    return {n: sorted(selected[:n], key=lambda p: p[0].name) for n in doses}

def copy_split(src_dataset, dst_dataset, split):
    for kind in ["images", "labels"]:
        src = src_dataset / kind / split
        dst = dst_dataset / kind / split
        dst.mkdir(parents=True, exist_ok=True)
        for item in sorted(src.iterdir()):
            if item.is_file():
                link_file(item, dst / item.name)

def copy_addons(dst_dataset, pairs, prefix):
    rows = []
    for img, lab in pairs:
        img_name = f"{prefix}_{img.name}"
        lab_name = f"{prefix}_{lab.name}"
        link_file(img, dst_dataset / "images" / "train" / img_name)
        link_file(lab, dst_dataset / "labels" / "train" / lab_name)
        rows.append({"source": prefix, "image": str(img), "label": str(lab), "copied_image": img_name})
    return rows

def write_dataset_yaml(dataset):
    data = {
        "path": str(dataset),
        "train": "images/train",
        "val": "images/val",
        "test": "images/test",
        "names": {0: "vape", 1: "lighter"},
    }
    with open(dataset / "dataset.yaml", "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)

def count_split(dataset, split):
    image_dir = dataset / "images" / split
    label_dir = dataset / "labels" / split
    image_count = len([p for p in image_dir.iterdir() if p.suffix.lower() in IMG_EXTS])
    label_count = len([p for p in label_dir.iterdir() if p.suffix.lower() == ".txt"])
    class_counts = Counter()
    box_count = 0
    for lab in label_dir.glob("*.txt"):
        for line in lab.read_text().splitlines():
            if not line.strip():
                continue
            cls = int(float(line.split()[0]))
            class_counts[cls] += 1
            box_count += 1
    return image_count, label_count, box_count, class_counts

def build_current_dataset(run_name, scraped=None, synthetic=None):
    scraped = scraped or []
    synthetic = synthetic or []

    if CURRENT.exists():
        shutil.rmtree(CURRENT)
    CURRENT.mkdir(parents=True, exist_ok=True)

    for split in ["train", "val", "test"]:
        copy_split(BASE, CURRENT, split)

    manifest_rows = []
    manifest_rows += copy_addons(CURRENT, scraped, "scraped")
    manifest_rows += copy_addons(CURRENT, synthetic, "synthetic")
    write_dataset_yaml(CURRENT)

    with open(CURRENT / "addon_manifest.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["source", "image", "label", "copied_image"])
        writer.writeheader()
        writer.writerows(manifest_rows)

    print("\n", run_name)
    for split in ["train", "val", "test"]:
        images, labels, boxes, class_counts = count_split(CURRENT, split)
        print({
            "split": split,
            "images": images,
            "labels": labels,
            "boxes": boxes,
            "vape_boxes": class_counts.get(0, 0),
            "lighter_boxes": class_counts.get(1, 0),
        })

    return CURRENT / "dataset.yaml"

DATA_ROOT.mkdir(parents=True, exist_ok=True)
RUNS_ROOT.mkdir(parents=True, exist_ok=True)

scraped_samples = sample_nested_pairs(SCRAPED, DOSES, seed=SEED)
synthetic_samples = sample_nested_pairs(SYNTHETIC, DOSES, seed=SEED)

ABLATION_SPECS = [
    ("v4_ablate_A0_real_only", [], []),
    ("v4_ablate_S88_scraped", scraped_samples[88], []),
    ("v4_ablate_S177_scraped", scraped_samples[177], []),
    ("v4_ablate_S355_scraped", scraped_samples[355], []),
    ("v4_ablate_Y88_synthetic", [], synthetic_samples[88]),
    ("v4_ablate_Y177_synthetic", [], synthetic_samples[177]),
    ("v4_ablate_Y355_synthetic", [], synthetic_samples[355]),
    ("v4_ablate_S355_Y355_combined", scraped_samples[355], synthetic_samples[355]),
]

for run_name, scraped, synthetic in ABLATION_SPECS:
    data_yaml = build_current_dataset(run_name, scraped=scraped, synthetic=synthetic)

    model = YOLO(MODEL)
    model.train(
        data=str(data_yaml),
        imgsz=IMGSZ,
        epochs=EPOCHS,
        batch=16,
        seed=SEED,
        deterministic=True,
        patience=100,
        project=str(RUNS_ROOT),
        name=run_name,
        exist_ok=True,
        cos_lr=True,
        device=0,
        workers=8,
        val=True,
    )

    # Preserve the exact add-on manifest beside the run before deleting temp dataset.
    run_dir = RUNS_ROOT / run_name
    shutil.copy2(CURRENT / "dataset.yaml", run_dir / "dataset.yaml")
    shutil.copy2(CURRENT / "addon_manifest.csv", run_dir / "addon_manifest.csv")

    shutil.rmtree(CURRENT)
    print("Deleted temporary dataset:", CURRENT)

 v4_ablate_A0_real_only
{'split': 'train', 'images': 837, 'labels': 837, 'boxes': 1317, 'vape_boxes': 870, 'lighter_boxes': 447}
{'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}
New https://pypi.org/project/ultralytics/8.4.64 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1280, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_ablate_A0_real_only, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs_data_ablation, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_A0_real_only, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    933412  ultralytics.nn.modules.head.Detect           [2, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,949,412 parameters, 9,949,412 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.6±0.2 ms, read: 1512.1±518.3 MB/s, size: 8943.8 KB)
train: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/train... 837 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 837/837 576.6it/s 1.5s
train: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/train.cache
val: Fast image access ✅ (ping: 1.0±0.5 ms, read: 421.4±192.4 MB/s, size: 3399.3 KB)
val: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/val... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183 389.2it/s 0.5s
val: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
val: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_A0_real_only/labels.jpg...
Image sizes 1280 train, 1280 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_A0_real_only
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100        20G      1.476      27.71    0.00574          5       1280: 100% ━━━━━━━━━━━━ 53/53 2.6it/s 20.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.1it/s 0.6s
                   all        183        302      0.235       0.25      0.184      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      25.9G      1.684       4.45   0.006076          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.0it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.4it/s 0.6s
                   all        183        302      0.315       0.28      0.216      0.128

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      25.9G      1.764      2.805    0.00659          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.7it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.328       0.38      0.273       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100        26G      1.738      2.484   0.006576          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.2it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.329      0.415        0.3      0.191

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100        26G      1.762      2.306   0.006607          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.9it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.7it/s 0.7s
                   all        183        302      0.471      0.425      0.399      0.252

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      26.1G      1.696      2.184     0.0063          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.8it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.512      0.489      0.462      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      26.1G      1.693       2.17   0.006244          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.2it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.559      0.458      0.451      0.285

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      26.2G      1.672      2.081    0.00603          5       1280: 100% ━━━━━━━━━━━━ 53/53 4.5it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.529      0.403      0.445      0.281

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      26.2G      1.694      2.066   0.006257          5       1280: 100% ━━━━━━━━━━━━ 53/53 3.9it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.5it/s 0.7s
                   all        183        302      0.442      0.483      0.432      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      26.2G      1.604      2.024   0.006221         16       1280: 55% ━━━━━━╸───── 29/53 1.4it/s 6.0s<16.7s

KeyboardInterrupt:

In [54]:
from pathlib import Path
import shutil

ROOT = Path("/workspace/uavape_v4_model_benchmark")
CURRENT = ROOT / "datasets" / "v4_data_ablation_20260610" / "_current_dataset"

if CURRENT.exists():
    shutil.rmtree(CURRENT)
    print("Deleted temp dataset:", CURRENT)
else:
    print("No temp dataset found.")

Deleted temp dataset: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset

In [55]:
A0_RUN = ROOT / "runs_data_ablation" / "v4_ablate_A0_real_only"

if A0_RUN.exists() and not (A0_RUN / "weights" / "best.pt").exists():
    shutil.rmtree(A0_RUN)
    print("Deleted incomplete A0 run:", A0_RUN)
else:
    print("No incomplete A0 run to delete, or it already completed.")

No incomplete A0 run to delete, or it already completed.

In [56]:
from pathlib import Path
import random, shutil, csv, yaml, os
from collections import Counter
from ultralytics import YOLO

DATA_ROOT = ROOT / "datasets" / "v4_data_ablation_20260610"
CURRENT = DATA_ROOT / "_current_dataset"
RUNS_ROOT = ROOT / "runs_data_ablation"

MODEL = "yolo26s.pt"
IMGSZ = 1280
EPOCHS = 100
SEED = 42

def link_file(src, dst):
    src = Path(src).resolve()
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    os.symlink(src, dst)

def sample_nested_pairs(pool_dir, doses, seed=SEED):
    pairs = list_yolo_pairs(pool_dir)
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    selected = shuffled[:max(doses)]
    return {n: sorted(selected[:n], key=lambda p: p[0].name) for n in doses}

def copy_split(src_dataset, dst_dataset, split):
    for kind in ["images", "labels"]:
        src = src_dataset / kind / split
        dst = dst_dataset / kind / split
        dst.mkdir(parents=True, exist_ok=True)
        for item in sorted(src.iterdir()):
            if item.is_file():
                link_file(item, dst / item.name)

def copy_addons(dst_dataset, pairs, prefix):
    rows = []
    for img, lab in pairs:
        img_name = f"{prefix}_{img.name}"
        lab_name = f"{prefix}_{lab.name}"
        link_file(img, dst_dataset / "images" / "train" / img_name)
        link_file(lab, dst_dataset / "labels" / "train" / lab_name)
        rows.append({"source": prefix, "image": str(img), "label": str(lab), "copied_image": img_name})
    return rows

def write_dataset_yaml(dataset):
    data = {
        "path": str(dataset),
        "train": "images/train",
        "val": "images/val",
        "test": "images/test",
        "names": {0: "vape", 1: "lighter"},
    }
    with open(dataset / "dataset.yaml", "w") as f:
        yaml.safe_dump(data, f, sort_keys=False)

def count_split(dataset, split):
    image_dir = dataset / "images" / split
    label_dir = dataset / "labels" / split
    image_count = len([p for p in image_dir.iterdir() if p.suffix.lower() in IMG_EXTS])
    label_count = len([p for p in label_dir.iterdir() if p.suffix.lower() == ".txt"])
    class_counts = Counter()
    box_count = 0

    for lab in label_dir.glob("*.txt"):
        for line in lab.read_text().splitlines():
            if not line.strip():
                continue
            cls = int(float(line.split()[0]))
            class_counts[cls] += 1
            box_count += 1

    return image_count, label_count, box_count, class_counts

def build_current_dataset(run_name, scraped=None, synthetic=None):
    scraped = scraped or []
    synthetic = synthetic or []

    if CURRENT.exists():
        shutil.rmtree(CURRENT)
    CURRENT.mkdir(parents=True, exist_ok=True)

    for split in ["train", "val", "test"]:
        copy_split(BASE, CURRENT, split)

    manifest_rows = []
    manifest_rows += copy_addons(CURRENT, scraped, "scraped")
    manifest_rows += copy_addons(CURRENT, synthetic, "synthetic")

    write_dataset_yaml(CURRENT)

    with open(CURRENT / "addon_manifest.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["source", "image", "label", "copied_image"])
        writer.writeheader()
        writer.writerows(manifest_rows)

    print("\n" + "=" * 80)
    print(run_name)
    print("=" * 80)

    for split in ["train", "val", "test"]:
        images, labels, boxes, class_counts = count_split(CURRENT, split)
        print({
            "split": split,
            "images": images,
            "labels": labels,
            "boxes": boxes,
            "vape_boxes": class_counts.get(0, 0),
            "lighter_boxes": class_counts.get(1, 0),
        })

    return CURRENT / "dataset.yaml"

DATA_ROOT.mkdir(parents=True, exist_ok=True)
RUNS_ROOT.mkdir(parents=True, exist_ok=True)

scraped_samples = sample_nested_pairs(SCRAPED, DOSES, seed=SEED)
synthetic_samples = sample_nested_pairs(SYNTHETIC, DOSES, seed=SEED)

ABLATION_SPECS = [
    ("v4_ablate_S88_scraped", scraped_samples[88], []),
    ("v4_ablate_S177_scraped", scraped_samples[177], []),
    ("v4_ablate_S355_scraped", scraped_samples[355], []),
    ("v4_ablate_Y88_synthetic", [], synthetic_samples[88]),
    ("v4_ablate_Y177_synthetic", [], synthetic_samples[177]),
    ("v4_ablate_Y355_synthetic", [], synthetic_samples[355]),
    ("v4_ablate_S355_Y355_combined", scraped_samples[355], synthetic_samples[355]),
]

for run_name, scraped, synthetic in ABLATION_SPECS:
    run_dir = RUNS_ROOT / run_name
    if (run_dir / "weights" / "best.pt").exists():
        print("Skipping completed run:", run_name)
        continue

    data_yaml = build_current_dataset(run_name, scraped=scraped, synthetic=synthetic)

    model = YOLO(MODEL)
    model.train(
        data=str(data_yaml),
        imgsz=IMGSZ,
        epochs=EPOCHS,
        batch=16,
        seed=SEED,
        deterministic=True,
        patience=100,
        project=str(RUNS_ROOT),
        name=run_name,
        exist_ok=True,
        cos_lr=True,
        device=0,
        workers=8,
        val=True,
    )

    run_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CURRENT / "dataset.yaml", run_dir / "dataset.yaml")
    shutil.copy2(CURRENT / "addon_manifest.csv", run_dir / "addon_manifest.csv")

    shutil.rmtree(CURRENT)
    print("Deleted temporary dataset:", CURRENT)

================================================================================
v4_ablate_S88_scraped
================================================================================
{'split': 'train', 'images': 925, 'labels': 925, 'boxes': 1440, 'vape_boxes': 993, 'lighter_boxes': 447}
{'split': 'val', 'images': 183, 'labels': 183, 'boxes': 303, 'vape_boxes': 203, 'lighter_boxes': 100}
{'split': 'test', 'images': 184, 'labels': 184, 'boxes': 420, 'vape_boxes': 255, 'lighter_boxes': 165}
New https://pypi.org/project/ultralytics/8.4.64 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.62 🚀 Python-3.12.3 torch-2.8.0+cu128 CUDA:0 (NVIDIA H100 80GB HBM3, 81079MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1280, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=v4_ablate_S88_scraped, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/workspace/uavape_v4_model_benchmark/runs_data_ablation, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_S88_scraped, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    477184  ultralytics.nn.modules.block.C3k2            [768, 256, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    136192  ultralytics.nn.modules.block.C3k2            [512, 128, 1, True]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1843712  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1    933412  ultralytics.nn.modules.head.Detect           [2, 1, True, [128, 256, 512]]
YOLO26s summary: 260 layers, 9,949,412 parameters, 9,949,412 gradients, 22.5 GFLOPs

Transferred 696/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.5±0.2 ms, read: 1278.3±1114.4 MB/s, size: 7221.1 KB)
train: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/train... 925 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 925/925 531.1it/s 1.7s
train: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/train.cache
val: Fast image access ✅ (ping: 0.5±0.2 ms, read: 338.3±240.6 MB/s, size: 3399.3 KB)
val: Scanning /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/val... 183 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 183/183 521.1it/s 0.4s
val: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/images/val/upload_image_20260603_195809_img_2331.jpg: 1 duplicate labels removed
val: New cache created: /workspace/uavape_v4_model_benchmark/datasets/v4_data_ablation_20260610/_current_dataset/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_S88_scraped/labels.jpg...
Image sizes 1280 train, 1280 val
Using 8 dataloader workers
Logging results to /workspace/uavape_v4_model_benchmark/runs_data_ablation/v4_ablate_S88_scraped
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      26.4G       1.45      26.06   0.007342         13       1280: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 36.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.6it/s 0.7s
                   all        183        302      0.611       0.21      0.215      0.152

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      26.4G      1.714       4.05   0.008303         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.5it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.7it/s 0.7s
                   all        183        302      0.277       0.41      0.211      0.117

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      26.5G      1.786      2.758   0.008529         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.4it/s 17.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.7it/s 0.7s
                   all        183        302      0.201      0.322      0.195      0.102

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      26.5G      1.831      2.668   0.008451         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.2it/s 17.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.402      0.401      0.329      0.202

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      26.5G      1.827      2.585    0.00959         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.7it/s 15.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.5it/s 0.7s
                   all        183        302      0.378      0.465      0.375      0.241

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      26.6G      1.751      2.299   0.008958         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.9it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.574       0.39       0.42      0.262

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      26.6G      1.714      2.195   0.008634         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.7it/s 15.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.468      0.445      0.447      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      26.7G      1.691      2.188   0.008226         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.1it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.3it/s 0.6s
                   all        183        302        0.5      0.469      0.451      0.305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      26.7G      1.707      2.113   0.008404         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.1it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.7s
                   all        183        302      0.606      0.487      0.512      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      26.8G      1.696      2.202   0.009017         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.0it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.582      0.512      0.531      0.321

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      26.8G      1.679       2.08   0.008287         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.4it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.621      0.554      0.552      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      26.9G       1.63      1.921   0.008095         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.4it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.584      0.609      0.564       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      26.9G      1.644       1.95   0.008344         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.6it/s 15.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.7s
                   all        183        302      0.524      0.572       0.53      0.344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100        27G      1.658      1.964   0.007911         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.0it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.637      0.574      0.593      0.394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100        27G       1.54      1.746   0.007558         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.2it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.6s
                   all        183        302      0.727      0.538      0.606      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      27.1G      1.523      1.722   0.007465         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.7it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.769      0.551      0.635      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      27.1G      1.575      1.822   0.007495         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.6it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.634      0.572      0.599      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      27.2G      1.518      1.719    0.00747         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.4it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 8.9it/s 0.7s
                   all        183        302      0.654       0.53      0.597      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      27.2G      1.524       1.77   0.007425         13       1280: 100% ━━━━━━━━━━━━ 58/58 5.0it/s 11.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.637      0.572      0.596      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      27.3G      1.537        1.7   0.007405         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.6it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.5it/s 0.6s
                   all        183        302      0.548      0.527      0.496      0.316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      27.3G      1.539      1.756   0.007893         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.8it/s 15.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.517      0.531      0.504      0.339

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      27.4G       1.51      1.708   0.007903         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.8it/s 15.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.7s
                   all        183        302      0.766      0.574      0.669      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      27.4G       1.47      1.615     0.0074         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.1it/s 14.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.3it/s 0.6s
                   all        183        302      0.725      0.582      0.663      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      27.5G      1.446      1.537   0.007435         13       1280: 100% ━━━━━━━━━━━━ 58/58 5.1it/s 11.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.0it/s 0.6s
                   all        183        302       0.64      0.549      0.609      0.424

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      27.5G      1.468      1.622   0.007431         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.9it/s 14.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.7s
                   all        183        302      0.615      0.525      0.564      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      27.6G      1.428      1.594   0.006951         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.1it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.6it/s 0.6s
                   all        183        302      0.714       0.57      0.671      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      27.6G      1.433      1.547   0.007288         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.7it/s 15.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.3it/s 0.6s
                   all        183        302      0.714      0.547      0.669      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      27.7G      1.397      1.518   0.006797         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.1it/s 18.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.694      0.604      0.675      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      27.7G      1.446      1.553   0.007648         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.6it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.1it/s 0.7s
                   all        183        302      0.712      0.613      0.672      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      27.8G      1.438      1.501   0.006997         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.8it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.0it/s 0.7s
                   all        183        302      0.702      0.671      0.695      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      27.8G       1.38      1.466   0.006411         13       1280: 100% ━━━━━━━━━━━━ 58/58 4.4it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 9.2it/s 0.7s
                   all        183        302      0.699      0.557      0.662      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      27.9G      1.363      1.487   0.006575         13       1280: 100% ━━━━━━━━━━━━ 58/58 3.8it/s 15.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 6/6 10.7it/s 0.6s
                   all        183        302      0.831      0.599      0.694      0.483
